### ISSUE TITLE
Critical edition pages: Dropdown

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#100]
We'd like to increase the size on the dropdown slightly (text size and width of box). If it's 100% now, we'd like to take it to 102%. It should only be this size on the desktop etc. Once you get down to mobile and the other dropdowns, then the critical edition dropdown would snap back to its current size so it was in line (size wise) with the other dropsdowns.

**Comment by nigelgbanks** [comment]
Ready for review on stage.

**Comment by awisnicki** [comment]
Too big now. Sorry. Let's make this 14px.

**Comment by nigelgbanks** [comment]
K reverted it back to it's original size of 14px.

**Comment by awisnicki** [comment]
Let's make this 14.5px and that will be a wrap. Closing...
