### ISSUE TITLE
Sticky header: Critical edition label

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#101]
Ideally, the sticky header would have the title of the specific page on which the user is, but if that's took tricky then it should at least be the title of the main critical edition page, so in this case "Livingstone's 1870 Field Diary"

![screen shot 2016-11-11 at 9 39 43](https://cloud.githubusercontent.com/assets/12518623/20221530/4978d9be-a7f7-11e6-842e-c700eb10a72b.png)

**Comment by awisnicki** [comment]
Also note that since there's no level 2 tile for this page (since it's part of the critical edition), "Spectral Imaging" in the sticky header is not purple when it should be.

**Comment by nigelgbanks** [comment]
If you follow the instructions on ticket:

https://github.com/livingstoneonline/livingstoneonline/issues/99

It should work as expected.

**Comment by awisnicki** [comment]
Yes, all looks sorted. thank you! closing this ticket.
