### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#102]
One additional question, the viewer (both in spectral mode and not) has a lot of buttons. Could we put titles on these so that a tooltip poped up when someone mouseover them. The buttons would be:

(left to right, top row):
menu
home
email
facebook
twitter
pintrest
zoom in
slider
zoom out
rotate
page no.
item details
transcription
compare spectral images
search

(left to right, second row)
spectral image type
processing details
download

**Comment by nigelgbanks** [comment]
Hmm seems like it would be clucky to have tooltips that repeat the text for their icons verbatim? Same goes for icons which are obvious like facebook, or the standard zoom buttons. Also pages don't have to be page numbers, maybe something else would suit better?

**Comment by awisnicki** [comment]
No, it's fine. This is for those audiences that don't understand the icons or are otherwise somehow impaired (this is something that is important to the NEH these days).

Adding these kinds of icons across the site is something I'd like to do in the next phase (there won't be as much as you might think, however). For now, however, let's take care of those that I've listed at top.

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks good on both the normal and spectral image page viewers. However, could you please modify the texts for the following:

Search box (both viewers): "Enter Your Search Terms" (no period at end; plus this new text)

Zoom (both viewers): "Zoom In/Out"

Select page (both viewers): "Select Image"

Spectral Image Type (spectral): "Select Spectral Image Type" (add "Select")

View Processing Details (spectral): "Display Processing Details" (change "View" to "Display")

Download Page Archive (spectral): "Download Archival Packet" (change "Page Archive" to "Archival Packet")

Arrows at the sides: "View Next Image" "View Previous Image"

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks good. Thank you. Closing out this ticket.
