### ISSUE TITLE
Critical edition dropdown: Title

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#108]
There's an issue with putting text into the Critical Edition dropdown. Right now, it's labeled exactly how we want: "Critical Edition - Table of Contents" but the issue is that when you go to the main site dropdown on mobile, in the list of site pages under the "Spectral Imaging" section, rather than "1870 Field Diary," what shows up is "Critical Edition - Table of Contents."

**Comment by nigelgbanks** [comment]
The way we build the table of contents has now changed, we'll chat about it a bit more on Thursday

**Comment by awisnicki** [comment]
OK, sounds good. I see that right now on mobile, in the TOC, we only have the six main sections, not any of the pages below them.

**Comment by awisnicki** [comment]
Sounds like this is still in progress, so will leave open, but feel free to close it if I've misunderstood.

**Comment by nigelgbanks** [comment]
This part of the issue has been handled, I've also updated the main menu. Other issues related to the table of contents, are handled in https://github.com/livingstoneonline/livingstoneonline/issues/106.

![screen shot 2017-06-12 at 20 48 38](https://user-images.githubusercontent.com/487373/27052122-8d31436a-4fb0-11e7-8b02-82acdd48efab.png)

**Comment by awisnicki** [comment]
I see that the main menu has been updated and that the text (for editions) in that menu, no longer says "Critical edition" etc. but rather gives the appropriate title, so all good & thank you! However, before we close this ticket, could you please explain:

1) How I add items to the main menu so that I know when I add editions, etc. in the future.
2) How I change the lead text in the critical edition dropdown. For instance, for the 1870 Field Diary it currently says "Critical Edition - Table of Contents." What do I do if I want to change that wording?

**Comment by nigelgbanks** [comment]
> How I add items to the main menu so that I know when I add editions, etc. in the future.

It's 100% the same as adding links to the 1870's field diary menu like we did on Thursday, except you choose the "main menu" instead to add links.

> How I change the lead text in the critical edition dropdown. For instance, for the 1870 Field Diary it currently says "Critical Edition - Table of Contents." What do I do if I want to change that wording?

It's currently hard coded here: https://github.com/livingstoneonline/livingstone_online_theme/blob/dev/js/custom.js#L102 

You can just ping me if you want to change the text, it applies to all the places where the table of contents is displayed.

**Comment by awisnicki** [comment]
OK, thanks. All good to know. One follow up question re: menus. For regular pages, I see that the path is straightforward and what I would expect. However, I looked at the critical editions and see the path is something like follows:

uuid/node/75c25c6c-c491-4059-b446-3562d7518c95

In this case, I would have normally put in:

spectral-imaging/livingstones-1871-field-diary-0

Would that still be OK? The question here seems to apply only to critical editions, I would guess, because of the issue of how these were previously rendering in the mobile menu.

**Comment by nigelgbanks** [comment]
Yup you can use either style of path, I tend to use "uuid's" as they are more portable, but you don't need to worry about that.

**Comment by awisnicki** [comment]
OK, perfect. I think it's a wrap on this.
