### ISSUE TITLE
Links to anchors

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#109]
I've found that when one page points to an anchor on another page, clicking on the linking often takes you to the wrong part of the other page. When you're ready to tackle this, I can show you some examples, but there are lots of them on these pages:

http://livingstoneonline.org/spectral-imaging/diary-across-hands-space-and-time-1
http://livingstoneonline.org/spectral-imaging/diary-across-hands-space-and-time-2
http://livingstoneonline.org/spectral-imaging/diary-across-hands-space-and-time-3

**Comment by nigelgbanks** [comment]
Hmm if some are farther down the page when the fixed header appears then the fixed title bar appears and sometimes covers the heading, is that what you are referring to?

**Comment by nigelgbanks** [comment]
Hmm might also have to do with the layout moving as images load in, as the browser jumps to the destination before all images are loaded, offsetting the position a bit.

**Comment by nigelgbanks** [comment]
I think this can be solved with a bit of jQuery that moves the scroll position again after all the images have loaded.

**Comment by awisnicki** [comment]
Yes, the issues you've described. Good to know that this can be addressed.

**Comment by nigelgbanks** [comment]
Should be working now. Not that this now adjusts for the header, so you may want to move some of the anchors to the **exact** line they are used. For example: 

http://livingstoneonline.org/spectral-imaging/creating-1870-field-diary#link14

Has the following HTML

```html
<p class="space2">
... essay (see Livingstone 1870a:[7]) so Livingstone clearly had the essay by that date.
<a id="link14" name="link14"></a>
</p>
<p><a ...>▲</a><strong> Annotation of one undertext.</strong> ...
```

So it scrolls to the end of that first paragraph rather than the start of the next one which I think is the intention. So instead something like:

```html
<p class="space2">
... essay (see Livingstone 1870a:[7]) so Livingstone clearly had the essay by that date.

</p>
<p><a id="link14" ...>▲</a><strong> Annotation of one undertext.</strong> ...
```
Would produce the desired result.

**Comment by awisnicki** [comment]
Yes, this looks like it's resolved. Thank you. It'd probably be best to review the anchors across the site with this change now in place, so that's a project I'll have to tackle in the spring. The good news is even if the relevant line appears somewhat below the sticky header, that's still fine.
