### ISSUE TITLE
Browse by Catalogue: Clear button

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#11]
For the clear button, please use the following text:

Clear search / browse choices

I also think you should make this button as long as the facet drop downs above it and have the spacing between this button and the facet dropdown above it be the same as between the other facet dropdowns.

**Comment by nigelgbanks** [comment]
Deployed to stage and ready for review.

**Comment by awisnicki** [comment]
Looks good. Well done and great idea to have this in the first place!
