### ISSUE TITLE
Share icons: changes

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#111]
I'd like to make a few small changes to the share icons that appear at the bottom of site pages.

1. Please add Google+ between the Twitter and Pintrest icons.
2. The first time a user mouses over an icon, it disappears and then reappears. I'd like to turn off that behavior.
3. Right now, we're using ShareThis for all of these icons. It works OK for Twitter and Facebook, but I don't like what it does with email. Are there any other options that we might explore here?

**Comment by nigelgbanks** [comment]
> Please add Google+ between the Twitter and Pintrest icons.

For the viewer as well? We don't have a whole lot of room for icons.

> Right now, we're using ShareThis for all of these icons. It works OK for Twitter and Facebook, but I don't like what it does with email. Are there any other options that we might explore here?

We could just embed a email link, then the browser should open the user's mail client provided by their OS.

**Comment by awisnicki** [comment]
Whoops! I wasn't clear. Re: Google+, I meant at the bottom of the page on level 3 pages. See attached. 

Same for point 2 above, with the icon disappearing and reappearing -- I also meant at the bottom of level 3 pages. 

With the manuscript viewer, there indeed isn't room for more icons so we can leave that as is. 

Finally, embedding the email links sounds good to me, so please go ahead and do that.

![screen shot 2017-01-12 at 14 01 18](https://cloud.githubusercontent.com/assets/12518623/21906161/c9e792a8-d8cf-11e6-9ee5-78814cb62fdc.png)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
This looks good. However, it looks like (as part of this?) you've added extra space at the bottom of the page, between the last line and the gray line that appears just above the icons. See screen shot, circled in red. Please close up this space so that the space above "Return to top" and the previous line (which is OK) is the same as the space below "Return to top" and the gray line (this space needs to be closed up). 
![screen shot 2017-06-07 at 16 28 14](https://user-images.githubusercontent.com/12518623/26902337-9868b49a-4b9e-11e7-8a5b-08e52decfbf2.png)

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Yes, perfect! Thank you!
