### ISSUE TITLE
Order of icons

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#112]
I'd like to change the default layout of the icons/boxes in the upper right-hand corner of the page. 

On full width, the current order is: share icons, search box, browse button.

![screen shot 2016-11-28 at 9 18 49](https://cloud.githubusercontent.com/assets/12518623/20673783/14754150-b54c-11e6-93f0-aa841691669c.png)

Once the screen starts to narrow, the order changes to: search box, browse button, share icons

![screen shot 2016-11-28 at 9 19 02](https://cloud.githubusercontent.com/assets/12518623/20673765/05853380-b54c-11e6-9239-3892a43520b9.png)

I'd like to keep this second variant throughout, so, in other words, the left to right order just needs to be changed on full width.

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
This looks good. Thank you. As I mentioned, the proportion of things has become distorted but I'll address that in separate tickets as part of a full review of the new theme later, so I'm closing this ticket now.
