### ISSUE TITLE
Timeline images: clickable

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#114]
In addition to the outstanding timeline issue (see https://github.com/livingstoneonline/livingstoneonline/issues/83), I'd also like to make the timeline images clickable, so, in short, users would have the option for each item of either clicking on the hyperlinked text or the image.

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks good, but please have them open in a new tab like the linked text for each item does.

**Comment by nigelgbanks** [comment]
K, now it opens in a new tab.

**Comment by awisnicki** [comment]
Indeed, it does. Thank you!
