### ISSUE TITLE
Long paths in topmenu

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#115]
Just a reminder that we need to look at the issue with long paths in the topmenu for which I had to turn to bit.ly as a temporary solution. Either of the images & texts options in the dropdown for the 1870 Field Diary is an example of this.

**Comment by nigelgbanks** [comment]
No longer using topmenu but there is now no limit on the length of a url in a menu link.

**Comment by awisnicki** [comment]
OK, we can discuss on Thursday. Also, on the back end, I can't see where to access importing content from remote FTP and updating modules via the Livingstone development settings so you'll have to show me that as well. Leave this ticket open for now as a reminder.

**Comment by awisnicki** [comment]
All sorted on this one. Thank you.
