### ISSUE TITLE
Coding manual: iFrame

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#116]
Right now, the link to the coding manual (last one on the this page: http://livingstoneonline.github.io/LEAP-ODD/leap.html) is forced to redirect from the site and open in a new window. I'd prefer for it to open in one of the site pages, in an iFrame, like we've done for the Mulit-Text viewer: http://livingstoneonline.org/spectral-imaging/three-versions-1870-field-diary

So, in other words, we'd have the title/overview text/arrows at the sides/icons at the bottom all generated per normal, but the center of the page would have an iFrame into which the Github page would be flown in or something like that. I could also upload the relevant HTML page right into our site if necessary.

This might be a bigger task and need to be part of our next contract, but if not I thought I'd note it here.

**Comment by nigelgbanks** [comment]
Currently embedded in an iframe:

http://livingstonestage.lib.umd.edu/resources/livingstone-online-tei-p5-encoding-guidelines

**Comment by awisnicki** [comment]
Looks good. Thank you. I'd like to do a little bit of theming revision on the iFrame so I'll leave this ticket open now so we can come back to it.

**Comment by awisnicki** [comment]
Also noting here that I need to review the location page.

**Comment by awisnicki** [comment]
And that we together need to review the multi-viewer page.

**Comment by awisnicki** [comment]
I'll be creating separate pages for the needed iFrame-coding-manual, multi-text viewer, and geolocation page tweaks, so am closing this ticket which was only serving as a placeholder.
