### ISSUE TITLE
Browse by Catalogue: links issue

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#117]
Please take a look at this page of the Catalogue:

http://livingstoneonline.org/islandora/search/%22liv%3A001429%22?full_record=1

If you scroll to the "Other Version(s)" column, you'll see that the word "link" is not hyperlinked as it should be to the URL available in the MODS record and, indeed, part of the relevant MODS record is missing here.

I see other such broken instances in the catalogue, but also some that work: http://livingstoneonline.org/islandora/search/liv_000111?full_record=1

**Comment by awisnicki** [comment]
Another link that's not working as it should.
![screen shot 2016-12-06 at 15 10 21](https://cloud.githubusercontent.com/assets/12518623/20943694/3e3c73fc-bbc6-11e6-82a1-bf93a668af2b.png)

**Comment by nigelgbanks** [comment]
Took a look into and it seems that the url in the data is invalid in two respects.

- The apostrophe must be "URL Encoded" to be properly escaped.
- The URL no longer points to a valid page.

The url for this object has this form in the MODS

```xml
<mods:relatedItem type="otherVersion">
  <mods:identifier>Helmsley Parish, http://www.helmsleyparish.org.uk/pics/Helmsley%20David%20Livingstone's%20letter.jpg (accessed 9 September 2015).</mods:identifier>
</mods:relatedItem>
```

So they apostrophe needs to be "URL Encoded" in the same sense that the spaces are "URL Encoded".

- Space Character becomes %20
- Apostrophe becomes %27

The other issue is that the page linked to no longer exists.

[http://www.helmsleyparish.org.uk/pics/Helmsley%20David%20Livingstone%27s%20letter.jpg](http://www.helmsleyparish.org.uk/pics/Helmsley%20David%20Livingstone%27s%20letter.jpg)

**Comment by nigelgbanks** [comment]
@awisnicki could you change the MODS file, and use the FTP import tool like you did with the recent images you added?

**Comment by awisnicki** [comment]
Yes, I can do this. I can across these two links by chance. Is there any way I can sort the table so it shows all the links in a row. That way I could go through them all and see if there are any other issues. Also, your answer seems to apply to the second problem I cite above. Does it also apply to the first? The issue there is not only that the link is broken, but that part of the normal text also doesn't show up.

**Comment by nigelgbanks** [comment]
I've applied a few more fixes, also this is the list of all items with Other Versions that have links: 

http://livingstoneonline.org/islandora/search/otherVersion_t:%22%2Ahttp:%22%22?full_record=1

**Comment by awisnicki** [comment]
Thanks very much for the link to the Catalogue with all links displayed. I've gone through this and fixed all those necessary; they'll get updated when I next update the MODS. 

We can close this ticket except there's one small bug in that when two entries appear in the Other Version column, then should be separated by a space, but right now they just run onto one another. For example, liv_002557:

Reginald Foskett, ed., The Zambesi Doctors: David Livingstone's Letters to John Kirk, 1858-1872 (Edinburgh: Edinburgh University Press, 1964), 140-144.Christie's (London), 25 September 2008, link (accessed 13 April 2015).

Corrected version (notice the space before the word "Christies":

Reginald Foskett, ed., The Zambesi Doctors: David Livingstone's Letters to John Kirk, 1858-1872 (Edinburgh: Edinburgh University Press, 1964), 140-144. Christie's (London), 25 September 2008, link (accessed 13 April 2015).

**Comment by nigelgbanks** [comment]
Should be fixed on production now.

**Comment by awisnicki** [comment]
Looks good. Thank you. Closing this ticket.
