### ISSUE TITLE
Capture low level errors during ftp import and display them on the error log tab.

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#118]
Currently some errors occur outside of the drupal context (import scripts, etc) this ticket is to capture that output and display it on the error page after running the import.

**Comment by nigelgbanks** [comment]
Nothing to really test here since it's low level but this is now sorted on stage.

**Comment by awisnicki** [comment]
OK, I'll go ahead and close this. This is something that can be reviewed as we proceed.
