### ISSUE TITLE
Browse by Catalogue: Colum Widths

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#12]
Please make the column widths on the new Catalogue the same as those on the existing catalogue on prod, etc.

**Comment by nigelgbanks** [comment]
This has been deployed to stage, but note that they will not be 100% the same, as a table is meant to be fluid (growing to the given size). But the min-width will be respected.

**Comment by awisnicki** [comment]
OK, what you've done looks good. However:

Please make the genre column somewhat wider by default.
Please make the title and date columns wider when the full table is shown.

**Comment by awisnicki** [comment]
I've sent you an email about this issue.

**Comment by nigelgbanks** [comment]
We walked though the widths in a call today and I adjusted them and they are now deployed to stage, so I think we can close this one.
