### ISSUE TITLE
Catalogue: Image loading issue

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#120]
liv_001696
liv_001957

are both private images and are in the "private" directory and are both coming up as private in the catalogue:

http://livingstoneonline.org/islandora/search/liv_001696
http://livingstoneonline.org/islandora/search/liv_001957

However, when one clicks on the red circle in the table to see the "Restricted Item" notice, rather than loading, the page freezes and nothing loads.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Indeed, fixed. Thank you!
