### ISSUE TITLE
Change the Import All button to no longer run the Solr Manuscript re-index.

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#122]
Or alternatively find a way to do a differential re-index so that it runs much faster.

**Comment by nigelgbanks** [comment]
Still runs but now should only update those manuscript which have children that have changed making it much faster.

**Comment by awisnicki** [comment]
OK, I'll test this out going forward, so will close this ticket and if I encounter any issues when doing the next import, I'll open a new ticket.
