### ISSUE TITLE
Theming issue on Firefox in Ubuntu

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#124]
Over the holidays I installed Ubuntu 16.04 on my home machine and in using Firefox discovered that there is a minor theming issue with the colored boxes on the home page, specifically, "Behind the Scenes"

![screenshot from 2017-01-01 22-31-04](https://cloud.githubusercontent.com/assets/12518623/21650639/3bf430f6-d26b-11e6-935e-e0df95cfd078.png)

It looked like this issue also came up on mobile versions. Perhaps this will be addressed by the theming rewrite?

**Comment by nigelgbanks** [comment]
Should be sorted.

**Comment by awisnicki** [comment]
This is fixed. Thank you.
