### ISSUE TITLE
Disable right-click download on MS Viewer

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#126]
The MS Viewer used to be configured so that if you right clicked it and try to download an image, that function was disable. However, it seems to have become enabled again. Please turn this off as soon as you get a moment.

**Comment by nigelgbanks** [comment]
I don't think this was ever implemented. Nonetheless I can disable right clicking but I cannot prevent people from downloading the image, anything displayed in the browser can be downloaded by the user.

**Comment by awisnicki** [comment]
The way you've done it is fine. Thank you. I realize that those determined enough can get around this plus screenshots are an option, but this adds the needed bit of deterrence for the majority of cases, so we're good to go. Four up and four down today -- a nice step forward.
