### ISSUE TITLE
Issues with viewers

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#127]
This was in an email, but I'm putting it here so that it doesn't get lost.

I've noticed two odd things -- I don't know if this is related to the work you've recently been doing. First, tooltips are flashing in an odd way, as at the top of the transcription on this page:

http://livingstoneonline.org/islandora/search?access=view_spectral&view_pid=liv%3A002570&view_page=0

Second, you'll note note in the ms viewer and in the multiviewer there's an odd additonal scrollbar that doesn't work. See attached screen shots. This appears to be tied to the height of the iframe which seems to need to be turned off.

![screen shot 2017-01-24 at 20 26 53](https://cloud.githubusercontent.com/assets/12518623/22488204/57d13b7c-e7d6-11e6-82c2-2eaaa9e8bacb.png)
![screen shot 2017-01-24 at 20 26 56](https://cloud.githubusercontent.com/assets/12518623/22488203/57d0b1ca-e7d6-11e6-8d6d-5dfd5e067a1a.png)

**Comment by nigelgbanks** [comment]
Just note for self the tooltip issue has been resolved. Double scroll bars still remain, they require a significant change in rendering (no longer using iframes), they were introduced to deal with bugs in the iPhone when rendering content in iFrames.

**Comment by nigelgbanks** [comment]
Should now be sorted on stage, further changes are needed to the xslt styles in LEAP-XSLT but we'll have to chat about that on Thursday.

**Comment by awisnicki** [comment]
OK, sounds like this is related to some of the issues I raised in #107. I'll leave this open for now so we don't forget about this.

**Comment by awisnicki** [comment]
Sounds like we'll come back to this so leaving open for now.

**Comment by nigelgbanks** [comment]
What we discussed on Thursday is captured in: https://github.com/livingstoneonline/livingstoneonline/issues/137, the issue that this ticket references has been resolved on stage. I move that we close this issue.

**Comment by awisnicki** [comment]
Motion granted!
