### ISSUE TITLE
Catalogue: width of access column

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#128]
This may be taken care of with the work you're already planning with the catalogue, but if not here's a ticket for it. The access column changes width (i.e., gets more narrow) when users click the full view box. I would like the width to stay fixed as it is when the box is not clicked.

**Comment by nigelgbanks** [comment]
Ready for review on stage.

**Comment by awisnicki** [comment]
Looks good. Closing this ticket. Thank you.
