### ISSUE TITLE
Viewable private files

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#129]
liv_000093 and liv_000094 should be private and are set up thus on our server, but both are accessible from the viewer. Any idea what's going on here? Are there other files like this?

**Comment by nigelgbanks** [comment]
They don't appear to be accessible?

<img width="1117" alt="liv_000094" src="https://cloud.githubusercontent.com/assets/487373/22626878/df4e22fa-ebae-11e6-8660-49a266e57030.png">
<img width="1117" alt="liv_000093" src="https://cloud.githubusercontent.com/assets/487373/22626879/df4f7362-ebae-11e6-9828-0cae1abf3a0e.png">

**Comment by awisnicki** [comment]
You're right. I just realized I probably looked at these while logged in. I'd forgotten that while logged in, the inaccessible is accessible.
