### ISSUE TITLE
Out of date local objects

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#130]
There are a few objects that have been out of date for a while on the Fedora server. I've tried various things to update them, but nothing has worked.
![screen shot 2017-03-21 at 12 39 46](https://cloud.githubusercontent.com/assets/12518623/24162477/a659fe3e-0e35-11e7-8b6c-a10c7ce13c86.png)

**Comment by nigelgbanks** [comment]
Two of the three have been sorted, but it looks like the .tif and .txt file for liv_001219_005 is missing from the FTP server?

/Livingstone-Directors/0_Core-Data/manuscripts/public/liv_001219

**Comment by awisnicki** [comment]
I think that the file in question here was left over by accident. It's now deleted and this is resolved.
