### ISSUE TITLE
Minor issue on Timeline page

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#133]
See attached, entry on the right below. & is not rendering properly on Browse by Addressee.
![img_6027](https://cloud.githubusercontent.com/assets/12518623/26444626/152c713e-4135-11e7-899c-30ebebf3c415.PNG)

**Comment by nigelgbanks** [comment]
Should be sorted.

**Comment by awisnicki** [comment]
This is resolved. Thank you. However, I also noticed this problem on Browse by Addressee:

http://livingstonestage.lib.umd.edu/in-his-own-words/addressee

Take a look at the entry for:  Ancient &amp; Honourable Company of Turners, Ladies &amp; Gentlemen... (1)

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Yes, resolved. Thank you!
