### ISSUE TITLE
Importing content

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#134]
On the back end, on the import content page, I'd like the listing ordered and renamed as follows:

Manuscript(s) => Manuscript Objects
Manuscript Page(s) => Manuscript Object Pages/Images
Manuscript Additional PDF(s) => Manuscript Object PDFs
Spectral Manuscript(s) => Spectral Manuscript Objects
Spectral Manuscript Page(s) => Spectral Manuscript Pages
[nothing] => Spectral Manuscript Images [I'd like this one added]
Illustrative Image(s) => Illustrative Images

We discussed this a while ago, but I never made a ticket for it.

**Comment by nigelgbanks** [comment]
Should be sorted though one point of clarification:

> Spectral Manuscript Page(s) => Spectral Manuscript Pages
> [nothing] => Spectral Manuscript Images [I'd like this one added]

These represent the same data in fedora a single object (there isn't a separate object per image, just one for all images of a page). So I've combined the two same as the Manuscript pages.

Spectral Manuscript Page(s) => Spectral Manuscript Pages/Images

**Comment by awisnicki** [comment]
See my note for #115. I can't access that section now, so will come back to this. Note, however, that I wanted to separate out Spectral Manuscript Pages and Images partly as a way for me to keep track of the number of images. So although there are 202 spectral manuscript pages, this really represents 3000 odd images so combining the two sounds like I won't be getting all that info. So, in other words, for regular manuscripts, one page = one image, hence why I combined then, but for spectral manuscripts, one page could = 17 images, etc. However, I'll review once I can access this.

**Comment by nigelgbanks** [comment]
Should have access now (a permission wasn't set for your account that now has been enabled).

**Comment by nigelgbanks** [comment]
The data on the server is grouped by "objects" not by the files uploaded, the information on the number of files is not currently present in the structure that is used to build that page, it will take some time to write it to add that information.

**Comment by awisnicki** [comment]
It looks like everything is sorted except the separate listing out of spectral images, so I'm leaving this open. Apologies for the extra work.

**Comment by nigelgbanks** [comment]
Ok but just to be clear this will take somewhere in the ball park of 6 or more hours.

**Comment by awisnicki** [comment]
Ah, I didn't realize that was the amount of time you meant! I think this is one of those cases where we need to imagine the ideal and leave it as that, imaginary. I'll go ahead and close this ticket. Thanks for your work in sorting out the rest of this.
