### ISSUE TITLE
Increase font size of admin bar 

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#135]

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks like you've set it to 18px. I think 14px will do. Please set it that size & then you can close this ticket.

**Comment by nigelgbanks** [comment]
Ready for review round 2.

**Comment by awisnicki** [comment]
Looks good. Thank you!
