### ISSUE TITLE
Add description to deploy page about which repositories it deploys

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#136]

**Comment by nigelgbanks** [comment]
Ready for review.

![screen shot 2017-06-13 at 16 25 27](https://user-images.githubusercontent.com/487373/27090374-f26bc5c6-5054-11e7-811e-1a16c239e0e9.png)

**Comment by awisnicki** [comment]
Two small typos to correct here, then please feel free to close out this ticket. Thank you!

1) "Responsible for the majority of the sites functionality." -- change "sites" to "site's"
2) "Contains the transcripts transforms and related CSS for displaying the generated HTML in both viewers." -- please put commas after "transcripts" and "transforms"

**Comment by nigelgbanks** [comment]
Made the changes.
