### ISSUE TITLE
For LEAP-XSLT Repo

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#137]
Update and add some documentation won't be using less going forward.

**Comment by nigelgbanks** [comment]
As a reminder I've moved my code to the branch theme-rewrite (so the use of update script won't deploy what was on the dev branch). This ticket can't be completed until we are ready to move to production.

**Comment by awisnicki** [comment]
Just a reminder that this is something that needs to be adjusted when we move to prod. Like #155, should this remain on hold?

**Comment by nigelgbanks** [comment]
Yes we can't do this until after we've done the migration.

**Comment by nigelgbanks** [comment]
Currently deployed to stage

**Comment by awisnicki** [comment]
This had to do with rendering of `<body>` around transcriptions? I believe that the place to review this is on the multi-text viewer:

http://livingstonestage.lib.umd.edu/spectral-imaging/three-versions-the-1870-field-diary
http://livingstonestage.lib.umd.edu/spectral-imaging/three-versions-the-1871-field-diary

Is that correct? If so, then it looks good to me and we can close this ticket, unless there's additional explanation needed for how I now update XSLT files?

**Comment by awisnicki** [comment]
Actually, I see an issue in the MS viewer. Here's one example:

http://livingstonestage.lib.umd.edu/in-his-own-words/catalogue?access=view_transcription&view_pid=liv%3A002647&view_page=0

On this page, first, the transcription is being rendered at too small a size. Second, you'll see in the screen shot, that a white space appears below the transcription.
![screen shot 2017-09-14 at 10 52 11](https://user-images.githubusercontent.com/12518623/30439949-c76a5cbe-993a-11e7-861c-914045e22941.png)

**Comment by awisnicki** [comment]
Also, when you open a longer transcription, the first page number is appearing under the sticky header whereas it should appear right below it.
![screen shot 2017-09-14 at 10 53 01](https://user-images.githubusercontent.com/12518623/30439993-f86f2006-993a-11e7-8f2e-914132384dea.png)

**Comment by nigelgbanks** [comment]
These two issues should be sorted now.

**Comment by nigelgbanks** [comment]
> Is that correct? If so, then it looks good to me and we can close this ticket, unless there's additional explanation needed for how I now update XSLT files?

You can just edit the css files like before.

**Comment by awisnicki** [comment]
Yep, it looks like both issues have been resolved. 

However, the text is still rendering too small. Compare the following page (transcription view) on prod: http://livingstoneonline.org/islandora/search?view_pid=liv%3A000504&view_page=0 and on stage: http://livingstonestage.lib.umd.edu/in-his-own-words/catalogue?access=view_transcription&view_pid=liv%3A000504&view_page=0 and you'll see that the stage text is smaller. It should be the size it is on prod.

Re: updating CSS/XSL via the old process sounds good. However, when I modify in dev branch, then run update_github command (so as to push to the stage and prod branches), I get the following error:

awisnicki2@ENGL-0B5E4A:~$ /Users/awisnicki2/GitHub/LEAP-XSLT/update_github.command ; exit;
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...4 completed.

**Comment by nigelgbanks** [comment]
> However, the text is still rendering too small. Compare the following page (transcription view) on prod: http://livingstoneonline.org/islandora/search?view_pid=liv%3A000504&view_page=0 and on stage: http://livingstonestage.lib.umd.edu/in-his-own-words/catalogue?access=view_transcription&view_pid=liv%3A000504&view_page=0 and you'll see that the stage text is smaller. It should be the size it is on prod.

The fonts are actually different, on production the css used with the xslt's references fonts like "Crimson Text" but doesn't actually load them so it defaults to one of the browser provided fonts. On stage it's actually using those fonts since the theme is loading them. 

> Re: updating CSS/XSL via the old process sounds good. However, when I modify in dev branch, then run update_github command (so as to push to the stage and prod branches), I get the following error:

Please don't make changes till after the move to production. 

The error would indicated that you have some issue with your installation of osx developer tools.

Try this:
https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path

**Comment by awisnicki** [comment]
OK, thanks! I'll leave this ticket open because I'd like to review the small text issue when we go up to prod. Also, no problem: I wont' make any changes to XSLT/CSS. I am applying the solution you've provided to the terminal error I had (thanks very much for that), but I'll wait to test it out till we're on prod.

**Comment by awisnicki** [comment]
I've reviewed the small font issue and it looks like I'm going to have to increase font size to 1.1 em and adjust other bits accordingly. Am I now able to push up changes in the LEAP-XSLT repo as per the previous workflow?

**Comment by nigelgbanks** [comment]
Yup feel free

**Comment by awisnicki** [comment]
I've looked slightly further into this and think something else may be causing the small font size, other than change in font. See screen shots. When I change the font, the font size remains small.

![screen shot 2017-10-31 at 06 33 35](https://user-images.githubusercontent.com/12518623/32222128-0d8aeb74-be06-11e7-90f2-8f392289eff3.png)

![screen shot 2017-10-31 at 06 33 44](https://user-images.githubusercontent.com/12518623/32222136-1254131a-be06-11e7-90cf-3a8bb62c6a95.png)

**Comment by awisnicki** [comment]
I've also found that manuscripts in the multitext viewer are rendering at the right size (e.g., http://livingstoneonline.org/spectral-imaging/three-versions-the-1871-field-diary), so I do think this issue is small text issue is arising from the ms. viewer.

**Comment by nigelgbanks** [comment]
For the example you give: 

http://livingstoneonline.org/in-his-own-words/catalogue?query=liv_000478&view_pid=liv%3A000478&view_page=0

It's using the style sheet: 
LEAP-XSLT/style.css

Which has this bit of css in it:

```css
/* 1. Textual divisions */
div.transcription.style {
  ...
  font-family: "source sans pro", calibri, arial, helvetica, sans-serif;
  font-size: 1em;
  ...
}
```

Now 1em is a relative font size so the font will be scaled against it's parent setting which is 14px. So the font will be 14px.

In the multitext viewer the 1871 field diary is using the stylesheet: 
LEAP-XSLT/style-1871-html.css

It also is using a relative font size:

```css
div.transcription.style-1871-html {
  ...
  font-family: "source sans pro", calibri, arial, helvetica, sans-serif;
  font-size: 1em;
  ...
}
```

The difference is the parent element from which it is scaled relatively to is 16px.

If you wish to have exactly 16px in both places use that rather than relative font sizes. So for both of these files you would use:

```css
  font-family: "source sans pro", calibri, arial, helvetica, sans-serif;
  font-size: 16px;
```

**Comment by awisnicki** [comment]
Thank you. Makes total sense. I just updated the CSS files and all seems resolved now.
