### ISSUE TITLE
RDF NINES

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#138]
Export UUID, Title, Byline, and Date created. so that Adrian can then update a csv and then nigel can write a script to update those pages.

**Comment by awisnicki** [comment]
Also, I've now reviewed the NINES page and for dc:type would like to add the following categories by default:

Illustration
Still Image
Dataset

The following could also be added, but only for those MODS records that had the corresponding fields in the genre category:

Map
Page Proofs 	 	 	 	
Typescript 	
Drawing

 Any way to do that without much trouble? If not, then we can ignore these four.

**Comment by awisnicki** [comment]
For collex:discipline, please add the following:

Political Science
Religious Studies

**Comment by awisnicki** [comment]
For collex:genre, please add the following:

Catalog
Collection 	
Correspondence
Ephemera 
Essay
Political Statement 	
Religion
Visual Art

**Comment by awisnicki** [comment]
For dc:title, we'd better add <title type="alternative"> from the MODS also. (Right now you just have <title>)

For <role:PBL>Livingstone Online</role:PBL>, perhaps we should make it <role:PBL>Livingstone Online (livignstoneonline.org)</role:PBL> ?

**Comment by nigelgbanks** [comment]
All the other aspects have been taken care of except for populating generating the csv file which will wait for when we do the final move to production (as content is likely to continue to change).

**Comment by awisnicki** [comment]
I think you need to restore some permissions on the back end, as I again can't see where to export the NINES files and don't have access to the FTP and dev update sections.

**Comment by awisnicki** [comment]
Could you go ahead before you go and restore the relevant permissions so I can review this?

**Comment by nigelgbanks** [comment]
You should have access now?

**Comment by awisnicki** [comment]
Yep, all good. Thank you!

**Comment by awisnicki** [comment]
I've reviewed the MODS and of the suggested changes above, I don't see that the following two have been addressed:

1. The following could also be added, but only for those MODS records that had the corresponding fields in the genre category:

Map
Page Proofs
Typescript
Drawing

Any way to do that without much trouble? If not, then we can ignore these four.

2. For role:PBLLivingstone Online</role:PBL>, perhaps we should make it role:PBLLivingstone Online (livignstoneonline.org)</role:PBL> ?

---
It's possible that after you previously reviewed these two requests, you decided that shouldn't be implemented (which is fine), but please confirm.

**Comment by nigelgbanks** [comment]
> 1. The following could also be added, but only for those MODS records that had the corresponding fields in the genre category:
Map
Page Proofs
Typescript
Drawing
Any way to do that without much trouble? If not, then we can ignore these four.

Seems to be working? 

- `liv_002681.rdf` has **Map** as a `<dc:type>` 
- `liv_003011.rdf` has **Page Proofs** as a `<dc:type>`
- `liv_003098.rdf` has **Typescript** as a `<dc:type>`
- `liv_002819.rdf` has **Drawing** as a `<dc:type>`

> For role:PBLLivingstone Online</role:PBL>, perhaps we should make it role:PBLLivingstone Online (livignstoneonline.org)</role:PBL> ?

Sure thing just changed it.

**Comment by awisnicki** [comment]
Re: URL in publisher, great. Thank you!

Re: Map, Page Proofs, etc., you're correct. My apologies for missing this. Closing the ticket.
