### ISSUE TITLE
Item missing images

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#140]
On prod, when I'm logged in and try to see the following item, the images don't show up:

http://livingstoneonline.org/islandora/search/%22liv%3A001766%22?view_pid=liv%3A001766

**Comment by nigelgbanks** [comment]
This appears to be sorted now (likely due to the issue with search we worked on via email last week).

**Comment by awisnicki** [comment]
You're right. There it is. Thank you!
