### ISSUE TITLE
Mobile: Page header not wrapping

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#142]
See screenshots. The items in the header are not breaking up into lines, but rather running off the screen. This seems to be happening on all levels of the site.
![img_6396](https://user-images.githubusercontent.com/12518623/27430073-c494d188-570c-11e7-8ea4-547b00261ce9.PNG)
![img_6397](https://user-images.githubusercontent.com/12518623/27430085-d3463ce4-570c-11e7-9e5a-6a6cdb377f7a.PNG)
![img_6398](https://user-images.githubusercontent.com/12518623/27430086-d3469b6c-570c-11e7-8e0c-82361538751a.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Resolved. Looks great.
