### ISSUE TITLE
Mobile: Home page theming

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#143]
See screen shot and compare to prod. Please put some padding on the left and right sides of the site title/subtitle and image. Also, the black box around the images is too heavy.
![img_6396](https://user-images.githubusercontent.com/12518623/27430211-534a9a48-570d-11e7-85c0-695d4c615d0b.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
The padding issue is resolve. Thank you!
Please make the border around the image 2px (as on prod). Right now it's 4px.
Finally, see screen shots. Could you fix the padding/sizing within the colored boxes so that it matches what's on prod?

Prod:
![img_6507](https://user-images.githubusercontent.com/12518623/27543903-32b4395a-5a51-11e7-814d-9c73b33fc51d.PNG)

Stage:
![img_6506](https://user-images.githubusercontent.com/12518623/27543922-4185ebd6-5a51-11e7-8d02-608e4fe92e8d.PNG)

**Comment by nigelgbanks** [comment]
> Please make the border around the image 2px (as on prod). Right now it's 4px.
> Finally, see screen shots. Could you fix the padding/sizing within the colored boxes so that it matches what's on prod?

Ok.

**Comment by awisnicki** [comment]
Thanks for adjusting the border. The colored nav tabs could still use, say, 1px of padding top and bottom, so that they're slightly taller.

**Comment by nigelgbanks** [comment]
K 1px add to the top and bottom of each link.

**Comment by awisnicki** [comment]
Perfect. It's a wrap on this. Thank you!
