### ISSUE TITLE
Mobile: Level 2 tile text wonky

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#144]
See screen shot. The text that appears inside the tiles is running off the screen.
![img_6398](https://user-images.githubusercontent.com/12518623/27430304-a4af70e8-570d-11e7-986c-7f5d220913e7.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
And this is fixed. Thank you.
