### ISSUE TITLE
Mobile: Level 3 carousel appearing

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#145]
See screen shot and compare to prod. The carousel is appearing on the mobile version of level 3 pages. It should not appear, but rather a version of the level 2 tile image should appear.
![img_6399](https://user-images.githubusercontent.com/12518623/27430354-e11678ba-570d-11e7-81e8-63f10b629b0a.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Yep, resolved perfectly. Thanks again.
