### ISSUE TITLE
Mobile: Page bottom icons

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#146]
Could we set it up, so that the icons break in groups, 3 and 3? I'd rather that one icon not appear alone on its own line.
![img_6400](https://user-images.githubusercontent.com/12518623/27430414-18f03bea-570e-11e7-90c4-16aa6eca8039.PNG)

**Comment by nigelgbanks** [comment]
Instead of making it break across lines I've got it to fit on a single line without changing the icon sizes or the spacing between them.

**Comment by awisnicki** [comment]
Yes, this looks great. Thank you!
