### ISSUE TITLE
Mobile: Sticky header running off screen

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#147]
The sticky header is getting pushed up above the screen. See screenshot.
![img_6401](https://user-images.githubusercontent.com/12518623/27430443-3c537e94-570e-11e7-8a97-b9131846ecb1.PNG)

**Comment by nigelgbanks** [comment]
I can't seem to reproduce this issue, though it may be cause I don't have the physical phone to test it on, also it could have fixed by other changes I made (but this at least on the surface doesn't seem likely). Can you check once more just to be sure?

**Comment by awisnicki** [comment]
yes, all sorted out. Thanks!

However, in reviewing this page (http://livingstonestage.lib.umd.edu/about-this-site/why-should-we-read-livingstone-s-manuscripts), I discovered that coding that Kathy previously set up for me for taking side by side images (on desktop) and puting them one above the other (on mobile) has not been carried over to the new theme. See screen shot. As you can see the images are distorted because they're remained side by side at this resolution whereas they should now be one above the other.
![img_6505](https://user-images.githubusercontent.com/12518623/27543459-d639360e-5a4f-11e7-904b-da00a7d8825e.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks good. Thanks for taking care of this.
