### ISSUE TITLE
Mobile: Addressee page

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#149]
The addressee page has an odd gray box in one corner. Also, some of the text is getting cut off. See circled.
![img_6404](https://user-images.githubusercontent.com/12518623/27430613-d154dbe6-570e-11e7-919d-54ab74c79f36.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Resolved. Thank you!
