### ISSUE TITLE
Mobile: Repository page

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#150]
In the table, the first cell (which lists repositories) is too wide on mobile. At this point, the text in this cell could be wrapping to a new line and the cell needn't be wider than what's visible in the screenshot.
![img_6405](https://user-images.githubusercontent.com/12518623/27430681-0d31d3f8-570f-11e7-8a87-e17eeb0432e7.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
This looks great, except that the first two columns now fit so perfectly on the page that users might not realize that there are additional columns to the right. Any way to signal this, perhaps by making the second column just a touch more narrow so that a sliver of the third column shows up?

**Comment by nigelgbanks** [comment]
I've made the change but to fit now some longer words must break with dashes.

![screen shot 2017-06-28 at 13 33 12](https://user-images.githubusercontent.com/487373/27637090-5a2d76d4-5c06-11e7-9251-3dff273e928f.png)

**Comment by awisnicki** [comment]
I think that's OK. Please make the country column the same width as the state column and then you can go ahead and close this ticket. Thanks very much!

**Comment by nigelgbanks** [comment]
K should be sorted both 'country', and 'state' are now 115px.

**Comment by awisnicki** [comment]
Perfect, thank you!
