### ISSUE TITLE
Mobile: Timeline page

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#151]
On the timeline page, neither the search boxes, nor images/text are showing up.
![img_6406](https://user-images.githubusercontent.com/12518623/27430709-36cd4c2e-570f-11e7-9f58-9bcccb025938.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks great. Thank you!
