### ISSUE TITLE
Mobile: MS and spectral viewers

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#153]
The items in the header are not centered and not distributed properly over the lines. Compare against prod. Also, horizontal spacing between items is a bit wonky.
![img_6409](https://user-images.githubusercontent.com/12518623/27430844-bee814d6-570f-11e7-873c-89a4b64e948a.PNG)

**Comment by awisnicki** [comment]
Same issue for spectral image viewer.
![img_6411](https://user-images.githubusercontent.com/12518623/27430962-2d5540a6-5710-11e7-964a-d8147fe5bf64.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
This issue on both the image and spectral image viewers has been resolved. Thank you.

However, it looks like in fixing this, on the spectral image viewer you set the colors off. See screen shots, there's lots of blue text here (and on the share icons) that shouldn't be blue and the transcription is coming up with out colors.

Also, given how little real estate there is here, on mobile, for both viewers, could you go ahead and remove the search box? It will still only be one click away (via closing the viewer), but this will open up some space. 

![img_6493](https://user-images.githubusercontent.com/12518623/27541948-6995217e-5a4b-11e7-94eb-34ab1e4841aa.PNG)
![img_6494](https://user-images.githubusercontent.com/12518623/27541947-6991a706-5a4b-11e7-8348-0a18147c8ddb.PNG)

**Comment by awisnicki** [comment]
Incidentally, the "blue" issue is also present on the multi-text viewer, which also has an odd blue set of dotted lines running across the top.
![img_6504](https://user-images.githubusercontent.com/12518623/27542395-c08ad752-5a4c-11e7-989a-a46dd054e4d5.PNG)

**Comment by nigelgbanks** [comment]
> However, it looks like in fixing this, on the spectral image viewer you set the colors off. See screen shots, there's lots of blue text here (and on the share icons) that shouldn't be blue and the transcription is coming up with out colors.

I can't seem to reproduce the issue with blue links or lines, likely this is from a font or css file failing to download? Do you still see this issue?

> Also, given how little real estate there is here, on mobile, for both viewers, could you go ahead and remove the search box? It will still only be one click away (via closing the viewer), but this will open up some space.

Sure thing.

**Comment by awisnicki** [comment]
Removal of the search bar looks good and I think helps open up the space.

In looking at that, I also notice that, on the spectral image viewer, I also notice that the "Processing Details" button needs to be moved down slightly so that it is level top and bottom with the "Color" (spectral image selector) tab.

Unfortunately, the "blue" issue is still there both on the multispectral viewer and on the multi-text viewer.

**Comment by nigelgbanks** [comment]
The blue issue was from reverting the changes I made to LEAP-XSLT its the css rules bleeding through. I've changed the stage box to use my branch on LEAP-XSLT for now (you won't be able to see changes to your XSLT / CSS on stage for the moment).

**Comment by awisnicki** [comment]
OK, I won't worry about the blue issue them. The processing details button appears to be moved down, so thanks for that. However, in reviewing this page, I also see that all the font looks too bit (16px). Please make the font on all the buttons etc. on this page 14px. This will bring it inline with other relevant parts of the site.

**Comment by nigelgbanks** [comment]
Change to 14px.

**Comment by awisnicki** [comment]
Looks good. Thank you!
