### ISSUE TITLE
Mobile: Slide out menu

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#154]
On the slide out menu, please close up the space between "Sections" at the top and the colored tabs below.
![img_6410](https://user-images.githubusercontent.com/12518623/27430928-0f195c9e-5710-11e7-80af-daa8c391b29a.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks good. Thank you!
