### ISSUE TITLE
Viewer: Item details date

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#157]
One of the dates in the Item Details section of the viewer looks like it's hard coded whereas it should be generated dynamically.
![img_6492](https://user-images.githubusercontent.com/12518623/27544435-c18640c8-5a52-11e7-91aa-d1c0f4883889.PNG)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks good. Thank you!
