### ISSUE TITLE
Migration to Production.

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#159]
Check that all non-top level Section pages don't have the Grid / Carousel images populated.

**Comment by nigelgbanks** [comment]
Check that the Empty section pages like 'Address' don't have any content in their body field.

**Comment by nigelgbanks** [comment]
From https://github.com/livingstoneonline/livingstoneonline/issues/106
> Links in dropdown (p.5) also looks good, although note that you've not brought down some of the specific configurations for links from prod -- some links are configured to open in a new window (on prod), but that formatting has been lost on stage. See, for instance, "Images & Transcriptions of the 1870 Field Diary" in the 1870 FD dropdown. I just changed this to target="_blank" to match prod, but it wasn't carried over automatically. In any case, this is minor and I can easily reimplement when the time comes, but just wanted to make you aware of this issue.

Need to dbl check links when do this manual aspect of the migration.

**Comment by awisnicki** [comment]
When doing the migration, remove the 'place holder' images from the nodes content for critical edition subpages.

**Comment by awisnicki** [comment]
I'm going to close #196 and will note that we need to resolve the table max-width issue on section pages. You mentioned that you'd take care of this, so this note is just a placeholder for that.

**Comment by awisnicki** [comment]
There are a number of different things cited in this thread. Can you clarify what it is that I should be reviewing and confirming here?

**Comment by nigelgbanks** [comment]
Nothing really for you to review they were just notes to myself to not forget certain things

**Comment by awisnicki** [comment]
OK, then I'll leave this open for now. When we migrate to prod, please feel free to close this when ready.
