### ISSUE TITLE
Desktop: Home page colored nav tabs

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#161]
Like you did on mobile, could you add about a pixel of padding above and below on the colored nav tabs for desktop and iPad. In other words, the extra pixels can there be for all versions of the site.

**Comment by awisnicki** [comment]
Actually, I think they need a pixel more so that height of the nav tabs on home matches height of the nav tabs on level 2/3 pages. In other words, the nav tabs should be exactly the same, theming-wise, in all places where they appear.

**Comment by awisnicki** [comment]
Still a slight mismatch between the nav tabs. See screen shot. The ones on home have too much padding at left and right.
![screen shot 2017-07-28 at 14 18 45](https://user-images.githubusercontent.com/12518623/28733009-ca65ab82-739f-11e7-8ae8-e5ef24f2eab3.png)

**Comment by awisnicki** [comment]
Also, note something seems to have gone off with the nav tabs on mobile. See screen shot.
![img_6860](https://user-images.githubusercontent.com/12518623/28741448-b01ceac4-73db-11e7-98d4-7a1a8a0d7cef.PNG)

**Comment by nigelgbanks** [comment]
> Still a slight mismatch between the nav tabs. See screen shot. The ones on home have too much padding at left and right.

Not sure what your asking for in this, but the mobile issue was sorted (old iphone bug).

**Comment by awisnicki** [comment]
What I was getting at is that, on the home page, desktop, there is extra padding on the nav tabs left and right. So, for instance, if you look at "About this Site" on the home page and compare it with a level 2 or 3 page, you will see that the text is the same size (that's good), but the colored button itself is wider on the home page. So whereas on level 2/3 if we say the width is 1, on home the width is 1.2 because of extra padding to the left and right of the word. Same for all the other buttons. Does that help?

**Comment by awisnicki** [comment]
P.S. Looks good on the mobile issue. Thank you!

**Comment by nigelgbanks** [comment]
Oh ic, in such a case there is no explicit padding set, the width changes depending on the available space. It's using a flex layout, I'll hack it though.

**Comment by awisnicki** [comment]
Looks good. Thanks!
