### ISSUE TITLE
All levels: Browse Collection button

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#162]
The text is the Browse Collection button looks slightly low. Please raise it a few pixels so that it is centered vertically.
![screen shot 2017-07-01 at 10 47 51](https://user-images.githubusercontent.com/12518623/27763535-e27a08cc-5e4a-11e7-93a8-59201b50a964.png)

**Comment by nigelgbanks** [comment]
The text is aligned with the other text:

<img width="580" alt="screen shot 2017-07-17 at 13 20 15" src="https://user-images.githubusercontent.com/487373/28267622-c8b92738-6af2-11e7-8a19-771425f51843.png">

Ahh sorry that's relative to the other text rather than to it's container, I'll sort it.

**Comment by awisnicki** [comment]
Fixed. Thank you!
