### ISSUE TITLE
Desktop: Home page institutional logos

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#164]
See the circled logos on the screen shot. They are too low. Please bring them up a bit. The NEH logo could also be slightly increased.
![screen shot 2017-07-01 at 10 57 54](https://user-images.githubusercontent.com/12518623/27763627-63afae8c-5e4c-11e7-8c4b-5440b530b661.png)

**Comment by awisnicki** [comment]
Also, as browser width narrows and logos go to a second line, at least two should do so right away. Please avoid having just one on the second line. Compare to prod.
![screen shot 2017-07-01 at 12 21 17](https://user-images.githubusercontent.com/12518623/27764148-088910be-5e58-11e7-8a6d-25813824ab20.png)

**Comment by awisnicki** [comment]
This looks good, except the NEH logo could still be slightly more increased in size. Also, it appears that the default now is for the logos to automatically break over two lines, but at largest screen resolution they should still be on one one line and only drop to two ones the resolution starts to narrow.

**Comment by nigelgbanks** [comment]
Made the NEH logo 300px long, I had to manually crop the other logo's in and image editing program to get spacing right.

**Comment by awisnicki** [comment]
Unfortunately, still doesn't look right. NEH is now too big; some of the others too small. I apologize that this is dragging out. Perhaps we should sort this one out in a call?

**Comment by awisnicki** [comment]
Just a reminder that we're ready to close this once you see if you can get a better version of the NEH logo.

**Comment by nigelgbanks** [comment]
Found a higher res version via google, couldn't use the eps or psd files on the branding site (don't have photoshop).

**Comment by awisnicki** [comment]
Looks awesome. Thanks!
