### ISSUE TITLE
All levels: Search box dropdown

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#170]
It looks like you've added a dropdown to the main site search box, whereas before the dropdown simply appeared when a user clicked in the search box. Although the click dropdown is an elegant solution, it also means extra clicking and if a user is trying to search multiple time, in only part of the site, it can quickly get cumbersome. Please restore this dropdown to how it is on prod.

**Comment by nigelgbanks** [comment]
Now it does both.

**Comment by awisnicki** [comment]
Ok, great. Thank you!
