### ISSUE TITLE
Desktop: Section page arrows

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#172]
The arrows at the side of the screen, on mouseover, give the title of the page to the right or left of the one the user is viewer. However, I believe we previously set the alt text on these to say "Previous Page" (left arrow) and "Next Page" (right arrow). Please restore this wording.

**Comment by awisnicki** [comment]
Sorry could we add "in section"

Previous page in section
Next page in section

**Comment by awisnicki** [comment]
Looks good. Thank you. In reviewing this, I realized that the arrows are missing on the Catalogue page. Can we put them in there? I realize that it will mean narrowing everything slightly. The Access and Creator columns definitely have some space to lose for this. And it looks like all the buttons could be narrowed without any harm. Are there other issues that I'm not seeing with making this change?

**Comment by nigelgbanks** [comment]
Should be sorted.

**Comment by awisnicki** [comment]
The buttons look good thank you! Unfortunately, it looks like you forgot to carry one more thing over: the text that appears above the table when "Full Record" is selected. See screen shot.
![screen shot 2017-08-03 at 15 21 57](https://user-images.githubusercontent.com/12518623/28942085-afc6c8b4-785f-11e7-8bac-eff192d84269.png)

**Comment by awisnicki** [comment]
And there's that implemented. Thank you.
