### ISSUE TITLE
Tablet: Timeline text

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#174]
The text next to the images on the Timeline starts wrapping prematurely as the browser window narrows. See screen shot. There is still plenty of space on the screen at this width, but the text is already wrapping.
![screen shot 2017-07-01 at 13 01 09](https://user-images.githubusercontent.com/12518623/27764368-858f7418-5e5d-11e7-9a7c-40b70cd4fd4e.png)

**Comment by awisnicki** [comment]
This is resolved. Thank you. However, in reviewing this, I realized some more theming might be helpful. See screen shot.
![screen shot 2017-07-24 at 17 41 38](https://user-images.githubusercontent.com/12518623/28548193-39b92cf8-7098-11e7-8bf0-f4c9c04291db.png)

**Comment by awisnicki** [comment]
The text inside the search boxes still appears to be 16px when it should be 14px. 

Also could you put a little padding (about 30px) below the search boxes so that the timeline is not so close. See screen shot.
![screen shot 2017-07-28 at 14 48 11](https://user-images.githubusercontent.com/12518623/28733903-dcccef52-73a3-11e7-9171-1da4aee8114a.png)

**Comment by nigelgbanks** [comment]
K changed to 14px, and changed the padding from 20px to 30px.

**Comment by awisnicki** [comment]
Unfortunately, the padding still does not look right. Make it 50px please.

For the search boxes, looks good. 

In reviewing these, however, it occurs to me that we need to do two things to be consistent. First, inside each search box, the second word should be capitalized. The search boxes and buttons to the right need titles text. The second word in the titles, per usual practice, should not be capitalized.

**Comment by awisnicki** [comment]
And a wrap on all the work here. Thanks again!
