### ISSUE TITLE
Multitext Viewer: Stying of text in panes

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#188]
The text in the panes, although generally styled properly, is not being fully styled per the relevant CSS. For instance, compare this page on stage and prod: http://livingstonestage.lib.umd.edu/spectral-imaging/three-versions-the-1870-field-diary and you'll see that the main title is not being properly rendered on stage.

**Comment by nigelgbanks** [comment]
This is covered by ticket: https://github.com/livingstoneonline/livingstoneonline/issues/137 we can't use recent changes to the XSLT until after the migration (during which we have to sort out the CSS issues of no longer rendering in an iframe).
