### ISSUE TITLE
Multitext Viewer: Containers in panes

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#190]
As we discussed, you are not rendering the `<body>` element in the panes. As a result, the text is not being contained properly and is spilling out of the panes left and right. How would you like to handle this? For instance, should we put an extra `<body>` element around everything (if that would even work) or an extra `<div>`, etc?

**Comment by nigelgbanks** [comment]
This is covered under: https://github.com/livingstoneonline/livingstoneonline/issues/137. We can't start modify the XSLT til after the migration.
