### ISSUE TITLE
Spectral image download page theming: minor change

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#197]
On the spectral image download page, please close up the space between the two columns so that it is half as wide as it is now. See screen shot for the region I'm referencing.
![screen shot 2017-08-10 at 6 57 04](https://user-images.githubusercontent.com/12518623/29167744-97c4d118-7d99-11e7-9036-49661b306894.png)

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
The issue is resolved. However, in reviewing this, I see that for some odd reason the items are being shown out of sequence in both columns:

![screen shot 2017-09-18 at 11 00 35](https://user-images.githubusercontent.com/12518623/30551623-ad387af0-9c60-11e7-8627-b6634c154a1f.png)

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Yes, looks good. Thank you!
