### ISSUE TITLE
Geolocation: height of window

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#198]
Please make the height of the window map the same size as the panes in the multitext viewer and the iFrame for the coding manual

**Comment by nigelgbanks** [comment]
Sorted.

**Comment by awisnicki** [comment]
Yes, this looks great. Thank you.

Can you tell me where this height is controlled (and also those of the multitext viewer and coding manual) in case I'd like to edit in the future?

**Comment by nigelgbanks** [comment]
**Google Map settings**
Configured via settings:
![google_map_settings](https://user-images.githubusercontent.com/487373/31685173-fe45d4da-b379-11e7-98c1-d1e2d69e4183.png)

![google_map_height](https://user-images.githubusercontent.com/487373/31685176-013461de-b37a-11e7-9d86-5519aea525ec.png)

**Multi-text viewer**
Hard coded in this [less file](https://github.com/livingstoneonline/livingstone_online_module/blob/dev/modules/transcript/less/livingstone-transcript.less). This file needs to be processed by [lessc](http://lesscss.org/) to generate the [css file](https://github.com/livingstoneonline/livingstone_online_module/blob/dev/modules/transcript/css/livingstone-transcript.css).

**Coding Manual**
Hard coded:
[livingstone_online_theme/templates/node/node--section-page-encoding-guidelines.tpl.php](
https://github.com/livingstoneonline/livingstone_online_theme/blob/dev/templates/node/node--section-page-encoding-guidelines.tpl.php#L113)

**Comment by awisnicki** [comment]
All looks good. Thanks for addressing these questions.
