### ISSUE TITLE
Geolocation: Search boxes

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#200]
Given the change discussed in #199 and the focus of this page, I think the first search box should be "Search by geolocation" rather than date. The search box could search two fields in the MODS records, those with Livingstone's locations and those with the normalized LoC location names

**Comment by awisnicki** [comment]
After further review of this with one of our collaborators, it's become clear that we'd not like to have the row of search boxes on this page, so let's plan to remove it.

Ideally, it'd be preferable to have a series of facets here. Would it be possible to have those on this kind of page rather than the search boxes? The facets would be drawn from the MODS.

**Comment by nigelgbanks** [comment]
> Ideally, it'd be preferable to have a series of facets here

It can't be driven by facets as this display is driven by Drupal Views (MySQL) rather than the Digital Catalogue which is driven by Solr which has support for facets.

I have removed the various searches which allows us to use caching so I can now display all 3000+ records on the map at once with reasonable performance.

**Comment by awisnicki** [comment]
Oh that's great. I think this works well as is. I don't see all 3,000 records currently, but I'm guessing they're just not on stage (I believe you said that before).

Once I add the "overview" text add the top, I can use that to explain how the page works, etc. 

When you push to prod, please leave the Geolocation page as unpublished and then I'll finalize it before it goes live.

Feel free reopen the comment if there's anything else to add about this, but otherwise thank you again on this one.
