### ISSUE TITLE
Geolocation: Buttons in upper-left

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#203]
Right now there are two options: Map and Satellite and one checkbox for each of them. What are the possibilities for what we could have here?

**Comment by awisnicki** [comment]
Can we make the default display to be Satellite view (rather than Map) but with both "labels" for Satellite and "terrain" for Map checked. See screen shot for the desired view, although note that it shouldn't be zoomed in like in the screen shot.

![screen shot 2017-08-14 at 12 18 29](https://user-images.githubusercontent.com/12518623/29283067-bd6c86d2-80ea-11e7-9d2e-f7eb8bbe4262.png)

**Comment by nigelgbanks** [comment]
> Right now there are two options: Map and Satellite and one checkbox for each of them. What are the possibilities for what we could have here?

These are all the possibilities.

> Can we make the default display to be Satellite view (rather than Map) but with both "labels" for Satellite and "terrain" for Map checked

Done except there isn't a "labels" for Map.

**Comment by awisnicki** [comment]
OK, this looks great. Thank you.
