### ISSUE TITLE
Manuscript Viewer: 2bugs

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#204]
I found two issues with the MS viewer:

1. Desktop: http://livingstonestage.lib.umd.edu/in-his-own-words/catalogue?f%5B%5D=dateRangeYear_mi%3A%221872%22&view_pid=liv%3A000049&view_page=0

See screen shot. The blue issue is here (though I assume that will be resolved per previous discussion), but also note how the display is working: Item details is crammed over to the left and there's the extra white gap in the middle.

![screen shot 2017-07-30 at 11 06 06](https://user-images.githubusercontent.com/12518623/29251662-7925bde4-801e-11e7-9b1e-2081f3b6c127.png)

2. Mobile: When one advances to a given page of a transcription, the page number should appear at the top below the header, but you'll note that in the attached image the page number actually goes under the header. This is how it rendered when I selected image/page 2.

![img_7019](https://user-images.githubusercontent.com/12518623/29251671-ace9b9b4-801e-11e7-90e1-5566c880ec83.PNG)

**Comment by nigelgbanks** [comment]
These issues have been addressed in previous tickets.

**Comment by awisnicki** [comment]
Indeed, they have. However, in reviewing the second one, I found a new bug. See screen shot. The background color of the transcription changes halfway across the screen.

![img_7198](https://user-images.githubusercontent.com/12518623/30551977-09675d18-9c62-11e7-83f5-907b61af1b77.PNG)

**Comment by nigelgbanks** [comment]
Should be sorted now

**Comment by awisnicki** [comment]
Looks good. Thank you!
