### ISSUE TITLE
Access and Upload Options

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#206]
I've been looking at stage and see that a few back end pages that are accessible from prod are no longer visible from stage. Screen shots below. These pages are helpful in that they let me add media to the site and also review content.

The following pages let me add one file or many files in bulk. The functionality of these may be covered by the filebrowser that's been added, but am noting just in case:

![screen shot 2017-09-07 at 11 46 54](https://user-images.githubusercontent.com/12518623/30175035-c1531c12-93c2-11e7-8c7d-f2cc698415d6.png)
![screen shot 2017-09-07 at 11 46 58](https://user-images.githubusercontent.com/12518623/30175036-c166de00-93c2-11e7-936c-fe9afc8c472d.png)

However, I don't believe the filebrowser will cover the functionality of the following page:

![screen shot 2017-09-07 at 11 47 09](https://user-images.githubusercontent.com/12518623/30175047-cd7e63ac-93c2-11e7-98db-e13467fba301.png)

This page lets me review and sort content in various forms, so it would be good to have it kept in the new site.

**Comment by awisnicki** [comment]
From a quick glance now, I don't see anything else useful that's missing on stage, but I'll try to do a more thorough review later today.

**Comment by awisnicki** [comment]
Here are a few more things that I can't currently see how to adjust on stage:

Where to change the title for Search bar and Browse button.
Where to edit text & link for image credits, site guide on home page; footer text on levels 2/3.
Where to initiate a manual backup of the database as well as where to set location.

**Comment by nigelgbanks** [comment]
You can now access the file browsers (on stage):

<img width="1440" alt="screen shot 2017-09-13 at 08 17 16" src="https://user-images.githubusercontent.com/487373/30364601-d927d884-985c-11e7-85e9-0b189bc68b16.png">

> This page lets me review and sort content in various forms, so it would be good to have it kept in the new site.

The content page is available in its normal location.

> Where to change the title for Search bar and Browse button.

It's hard coded.

> Where to edit text & link for image credits, site guide on home page; footer text on levels 2/3.

It's all hard coded.

> Where to initiate a manual backup of the database as well as where to set location.

Backups are not setup for staging server (don't want to accidentally overwrite production, etc). The testing of this will have to wait for deployment to production.

**Comment by awisnicki** [comment]
I see Filebrowser and you're right that the content page is in the normal location. Not sure how I previously missed it!

For the hard-coded items, can you tell me the location of each of them in case I want to edit in the future. For instance, I plan to edit the footer text soon.

Re: backups, OK, I'll revisit.

**Comment by nigelgbanks** [comment]
Search:
https://github.com/livingstoneonline/livingstone_online_theme/blob/dev/includes/alter.inc#L18-L19

Footer:

https://github.com/livingstoneonline/livingstone_online_theme/blob/dev/templates/system/page.tpl.php#L139-L141

**Comment by nigelgbanks** [comment]
I'll create a seperate ticket to track backups on production

**Comment by awisnicki** [comment]
Thanks for Search and Footer links. Please note that we still need: Browse and text/link for "image credits" and "site guide" on the home page.

**Comment by nigelgbanks** [comment]
Oh sorry that is here:

https://github.com/livingstoneonline/livingstone_online_theme/blob/dev/templates/system/page--front.tpl.php#L95-L103

**Comment by awisnicki** [comment]
Almost there. Still need the Browse link.

**Comment by nigelgbanks** [comment]
Browse by widget: https://github.com/livingstoneonline/livingstone_online_module/blob/dev/theme/livingstone-browse-collection-block.tpl.php

**Comment by awisnicki** [comment]
Great. Thank you!
