### ISSUE TITLE
Issue with Multitext Viewer

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#207]
I went to access this page today: http://livingstoneonline.org/his-own-words/multiple-versions-text

And got the following error. See screen shot. I've seen this before, but it only happens occasionally. For instance, when I accessed the page just now it was fine.

![screen shot 2017-09-12 at 13 24 07](https://user-images.githubusercontent.com/12518623/30349353-5a034630-97d8-11e7-961d-54e5637dbc27.png)

**Comment by nigelgbanks** [comment]
I've added a caching layer that should hopefully cut down on the timeouts occuring.

**Comment by awisnicki** [comment]
Ok, sounds good. Thanks very much. I'll keep an eye on this and let you know if it comes up again.
