### ISSUE TITLE
Multiple Versions of the Text times out too many transcriptions to generate, needs to be ajax

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#208]
Times out and fails to render:
http://livingstonestage.lib.umd.edu/in-his-own-words/multiple-versions-the-text

Requires a rewrite.

**Comment by nigelgbanks** [comment]
This is now sorted, the page load in stages after selecting which to view.

**Comment by awisnicki** [comment]
This looks good, but I see that something is off with padding on the right in the panes. See screen shot, pane on the right. This is as far right as I can scroll over, but you can see that there's a bit more on the page.
![screen shot 2017-09-21 at 11 30 19](https://user-images.githubusercontent.com/12518623/30707213-68571060-9ec0-11e7-99ac-828a64bd5a79.png)

**Comment by nigelgbanks** [comment]
It was exactly flush with the item details, I've added the same left padding to the right for the item details.

**Comment by awisnicki** [comment]
Ok, this looks great. Thank you!
