### ISSUE TITLE
Missing menu for Final Manuscripts

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#209]
Need to manually create the menu for:

http://livingstonestage.lib.umd.edu/in-his-own-words/livingstones-final-manuscripts-1865-1873

http://livingstoneonline.org/his-own-words/livingstones-final-manuscripts-1865-1873

**Comment by awisnicki** [comment]
Also the level two boxes for this edition is again not rendering correctly:

![screen shot 2017-09-14 at 13 11 26](https://user-images.githubusercontent.com/12518623/30446283-446cb3b6-994e-11e7-829c-2ac3f7d4be32.png)

**Comment by nigelgbanks** [comment]
What is the issue? It looks the same as it did on stage the previous week (I haven't the theme code changed the grid theme code since the last round of feedback on stage).

**Comment by nigelgbanks** [comment]
Is it the height of the last item (it appears taller than the others)?

**Comment by nigelgbanks** [comment]
Looks like it was the image file I uploaded (was the wrong size) should be sorted now.

**Comment by awisnicki** [comment]
Yes, indeed, it's sorted now.

**Comment by nigelgbanks** [comment]
K the menu is in place now, although still have issue 208 to contend with

**Comment by awisnicki** [comment]
Sorry, I'm not clear by what you mean by adding the menu. 

I see two issues, but this may be different from this:
1. The Final Manuscripts edition does not appear in the top menu.
2. All the pages but the home page don't have the Critical Edition dropdown.

**Comment by nigelgbanks** [comment]
The other two issues, have been handled as well.

**Comment by awisnicki** [comment]
Looks good. Thank you! Note that the Final Manuscripts dropdown includes the "TEI Encoding Guidelines" twice. The first iteration points to the following external page: http://livingstoneonline.github.io/LEAP-ODD/leap.html This iteration can be removed so that there is only the one point to the new internal guidelines page you created.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
OK, looks good. Thank you!

**Comment by awisnicki** [comment]
Yes, looks good. Thank you. If I find any other instances of this once we move to prod, I'll just fix this myself.

**Comment by awisnicki** [comment]
Yes, looks good. Thank you.
