### ISSUE TITLE
Addressee page issue

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#210]
The addressee page is missing the top section of the page with carousel, overview, etc.

http://livingstonestage.lib.umd.edu/browse/addressee

**Comment by awisnicki** [comment]
Similar issue for this page: http://livingstonestage.lib.umd.edu/behind-the-scenes/acknowledgments

**Comment by nigelgbanks** [comment]
The outbound link got reset in the migration it's now been changed to:

http://livingstonestage.lib.umd.edu/in-his-own-words/addressee

So http://livingstonestage.lib.umd.edu/browse/addressee is no longer linked to (page is auto-generated by Drupal, but we have no links to it).

> Similar issue for this page: http://livingstonestage.lib.umd.edu/behind-the-scenes/acknowledgments

I can't seem to reproduce this issue.

**Comment by nigelgbanks** [comment]
Though there is a seperate issue with the <hr> element being hidden (looks like more manual changing of the content will be required).

**Comment by awisnicki** [comment]
Thanks for sorting Addressee. Re: the <hr/> on Acknowledgments and, indeed, many other pages, note that we always add that at the top of Main Text section. Perhaps, the path of least resistance is to leave that as is and simply remove it from the bottom of the overview section? Previously it did not appear at the bottom of the overview, hence why we added it manually to every page. In any case, feel free to resolve this however, you think is easiest/best.

**Comment by nigelgbanks** [comment]
Ya I was hiding it before since the overview section had two matching hr elements, but now I'll just remove them all and add a default one for when the overview is empty.

**Comment by awisnicki** [comment]
OK, sounds good. I'm going to close this and continue in #214 since this is related to that.

**Comment by awisnicki** [comment]
I'm going to reopen this issue as I see at least one instance (on the site guide page) of the link pointing to the wrong URL: http://livingstonestage.lib.umd.edu/browse/addressee rather than the correct one. Perhaps do a batch replace in case there are other such instances also.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
OK, thank you. If any other instances come up after migration to prod, I'll take them of them.
