### ISSUE TITLE
Repository page issue

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#211]
The font on the repository page appears to be a larger size than the font on most other pages:

http://livingstonestage.lib.umd.edu/in-his-own-words/repository

Compare it to a regular content page.

**Comment by nigelgbanks** [comment]
They are both set to:
The text in the table? It seems to be the same as the section page content.

```css
    font-family: 'Source Sans Pro', sans-serif;
    font-size: 16px;
```

Which text in particular?

**Comment by awisnicki** [comment]
I figured out the issue. The text in the table on prod (http://livingstoneonline.org/his-own-words/repository) is 14px. Please set it to that same size here. Or, alternately, make the text in the repository table the same size as the text in the Browse by Catalogue table (which is smaller than what Repsitory is now on stage).

**Comment by nigelgbanks** [comment]
I've set it to 14px.

**Comment by awisnicki** [comment]
Looks good. Thank you!
