### ISSUE TITLE
Timeline page issue

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#212]
The timeline page only has a few items on it, but perhaps this is OK?

http://livingstonestage.lib.umd.edu/in-his-own-words/timeline

**Comment by nigelgbanks** [comment]
Only had a small subset imported for demo purposes I've started an import for the rest so you can review should take about an hour.

**Comment by awisnicki** [comment]
Ok, thanks for doing this.

**Comment by nigelgbanks** [comment]
Wifi is spotty on the train so the import kept cutting out, I'll run the import tomorrow.

**Comment by awisnicki** [comment]
OK, thanks for doing that. I will say what I saw looked fine, so I don't anticipate any issues here.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Yes, looks good. Thank you!
