### ISSUE TITLE
Critical edition theming

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#213]
The theming at the top of a given critical edition page does not match prod. See screen shots below. Specifically:
1. Reduce spacing below critical ed dropdown and the main title
2. Reduce spacing below the small byline and the gray line that follows.

Prod:
![screen shot 2017-09-14 at 11 53 19](https://user-images.githubusercontent.com/12518623/30442949-94a86b5a-9943-11e7-9a6b-07ce28689972.png)

Stage:
![screen shot 2017-09-14 at 11 53 22](https://user-images.githubusercontent.com/12518623/30442960-993acf5a-9943-11e7-8a4a-aae8e27a64b4.png)

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks great. Thank you!
