### ISSUE TITLE
Overview gray lines

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#214]
See screen shot. This issue appears to be present on all pages with a TOC.
![screen shot 2017-09-14 at 12 03 03](https://user-images.githubusercontent.com/12518623/30443401-f4fe5f68-9944-11e7-8a11-5277f2dea528.png)

**Comment by nigelgbanks** [comment]
Gotta edit all those pages to move it into the overview field.

**Comment by awisnicki** [comment]
So you're suggesting taking all the TOCs and moving them into the overview section? 

I'm wondering if it wouldn't be easier to leave things as is here, so the following would be needed:

1. In-text <hr/>s need to be made darker. This is true regardless of whether we make other changes, as I believe we might occasionally use <hr>s elsewhere in the site.
2. The overview section as a rule should not have a gray line below. That's how it was set up before, so to compensate we always started the main text with an <hr>.

I think this is all that is needed to get around the issue of moving all the TOCs (of which there are many). But happy to hear your thoughts on how to approach this.

**Comment by nigelgbanks** [comment]
I'm gonna move them into the overview section, it won't take too long and it's the less hacky of the two solutions. I'll change the styling of the hr to match that of the overview as well (the overview doesn't actually use hr tag it just uses border property.

**Comment by awisnicki** [comment]
Agreed that it's less hacky! I just didn't want to add extra work. I'll leave it with you then. Just let me know when you want me to review.

**Comment by nigelgbanks** [comment]
All the pages affected have now been changed.

**Comment by awisnicki** [comment]
This looks good. Thank you very much for doing this. 

Could you please make the following minor theming adjustments. Also see screen shots.

The overview section contains black text. Please increase the margin bottom on this to 16px.
![screen shot 2017-09-21 at 11 03 41](https://user-images.githubusercontent.com/12518623/30706705-d6e8f7c0-9ebe-11e7-958e-15d96a9fa23c.png)

The overview section also contains blue (hyperlinked) text -- the TOCs you just moved. Please reduce the margin botton on this to 6px and increase the line height to 1.6
![screen shot 2017-09-21 at 11 00 41](https://user-images.githubusercontent.com/12518623/30706771-1676d2d6-9ebf-11e7-90b8-b00287f8078e.png)
![screen shot 2017-09-21 at 11 01 17](https://user-images.githubusercontent.com/12518623/30706772-1693efb0-9ebf-11e7-894d-661f9482394d.png)

Finally, this is unrelated to the above but is a similar kind of theming change. Please increase the margin-bottom on the critical ed dropdown to 26px.
![screen shot 2017-09-21 at 11 09 22](https://user-images.githubusercontent.com/12518623/30706836-3d2826aa-9ebf-11e7-839f-8cdd514cbe4c.png)

**Comment by nigelgbanks** [comment]
K other changes are now pushed

**Comment by awisnicki** [comment]
All changes on this look good, except the space below the hyperlinked table still needs slightly to be reduced. See screen shot.
![screen shot 2017-09-25 at 09 24 32](https://user-images.githubusercontent.com/12518623/30813650-9f0ed834-a1d3-11e7-915e-feff59dcb39b.png)

**Comment by awisnicki** [comment]
Also note small erroneous space introduced on this page: http://livingstonestage.lib.umd.edu/spectral-imaging/the-diary-across-hands-space-and-time-3

![screen shot 2017-09-25 at 09 27 27](https://user-images.githubusercontent.com/12518623/30813760-e8981fa6-a1d3-11e7-9486-16ef69b6efa6.png)

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
All looks great. Thank you!
