### ISSUE TITLE
Byline width

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#215]
The byline needs to be made slightly wider to match prod. Note that on stage the text wraps before it does on prod.

Stage:
![screen shot 2017-09-14 at 12 16 18](https://user-images.githubusercontent.com/12518623/30443882-bc9c531c-9946-11e7-91a7-8c5f52e3e5b1.png)

Prod:
![screen shot 2017-09-14 at 12 16 18](https://user-images.githubusercontent.com/12518623/30443866-aab11d40-9946-11e7-9343-808f214426cd.png)

**Comment by nigelgbanks** [comment]
Changed the font size so that it matches prod

**Comment by awisnicki** [comment]
Looks great! Thanks!
