### ISSUE TITLE
In-text table display

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#216]
The formatting around in-text tables has changed. Compare the table on this page: 

http://livingstonestage.lib.umd.edu/spectral-imaging/manuscript-citation-and-file-naming-practices

with prod. All the lines are showing up around the table (not desirable) whereas they weren't before:

Stage:
![screen shot 2017-09-14 at 12 40 20](https://user-images.githubusercontent.com/12518623/30444975-43916d00-994a-11e7-86f3-1f2cb24b043c.png)

Prod:
![screen shot 2017-09-14 at 12 42 16](https://user-images.githubusercontent.com/12518623/30444981-46a3cff6-994a-11e7-868c-5e7c13420e6e.png)

**Comment by nigelgbanks** [comment]
This should now be sorted.

**Comment by awisnicki** [comment]
Yes, looks good. Thank you.
