### ISSUE TITLE
Edition URLs

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#217]
Each of the editions in the site have some common pages, among them the following:

Edition Guide
1871 FD: http://livingstoneonline.org/spectral-imaging/edition-guide-1
1870 FD: http://livingstoneonline.org/spectral-imaging/edition-guide
Bambarre: http://livingstoneonline.org/spectral-imaging/edition-guide-0

Project Team
1871 FD: http://livingstoneonline.org/spectral-imaging/project-team-1
1870 FD: http://livingstoneonline.org/spectral-imaging/project-team
Bambarre: http://livingstoneonline.org/spectral-imaging/project-team-0

Acknowledgments
1871 FD: http://livingstoneonline.org/spectral-imaging/acknowledgments-1
1870 FD: http://livingstoneonline.org/spectral-imaging/acknowledgments
Bambarre: http://livingstoneonline.org/spectral-imaging/acknowledgments-0

The URLs for these are similar, but of course not identical and point to different pages based on the given edition. I mention this because I see that some of the edition URLs throughout the editions on stage (and on the site guide page: http://livingstonestage.lib.umd.edu/about-this-site/livingstone-online-site-guide) have gotten mixed up. Is there a way to compare against prod other than manually?

**Comment by awisnicki** [comment]
Issue #222 touches on this.

**Comment by nigelgbanks** [comment]
I'm going to have to go through them manually, the issue arised from random ordering when the alias were generated on the deployment to stage. I'm gonna change them to have explicit names like:

- http://livingstoneonline.org/spectral-imaging/1870-acknowledgments
- http://livingstoneonline.org/spectral-imaging/1871-acknowledgments
- http://livingstoneonline.org/spectral-imaging/bambarre-acknowledgments

**Comment by awisnicki** [comment]
Ok, let me know if I can help with this. 

There is also the following, in addition to the ones cited above:

Project Documentation
1871 FD: http://livingstonestage.lib.umd.edu/spectral-imaging/project-documentation-0
1870 FD: http://livingstonestage.lib.umd.edu/spectral-imaging/project-documentation

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
OK. Thank you. I can take it from here, once we go to prod, and change myself in case any instances are missed.
