### ISSUE TITLE
Back end order for creating section pages

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#219]
Please rearrange the order of items on the "Create Section Page" page from the top down as follows:

Pre-Title
Title
Subtitle
Main Text
Byline
Critical edition
Overview
Teaser

[rest of the order is fine]

Also, note that the overview and teaser sections will rarely have a lot of text, so both can be cut to about 1/3 their current height.

For the author and editor sections, please add the following descriptive text: Please give the name in the last name, first name format: "Wisnicki, Adrian S."

Finally, the "date" and "outbound link" sections can be removed as we don't use them.

**Comment by nigelgbanks** [comment]
> Please rearrange the order of items on the "Create Section Page" page from the top down as follows:

Done.

> Also, note that the overview and teaser sections will rarely have a lot of text, so both can be cut to about 1/3 their current height.

Unfortunately this is not an exposed setting I can tweak.

> For the author and editor sections, please add the following descriptive text: Please give the name in the last name, first name format: "Wisnicki, Adrian S."

Done.

> Finally, the "date" and "outbound link" sections can be removed as we don't use them.

Date has been removed but we do use "outbound link" on one section page, the one used to link to the digital catalogue and pass some parameters in via the url. The "The Livingstone Spectral Image Collection" node does this, so we can't remove it.

**Comment by awisnicki** [comment]
OK, all looks good. Thank you. 

Can you let me know where this is edited so I can do it myself in the future if necessary.

**Comment by nigelgbanks** [comment]
You'll need to be logged in as the admin user to change the ordering or the fields.

<img width="786" alt="navigate" src="https://user-images.githubusercontent.com/487373/31578128-cbaa4592-b112-11e7-9a84-19d3f4020df6.png">

<img width="1440" alt="edit" src="https://user-images.githubusercontent.com/487373/31578129-cf840d74-b112-11e7-8c3b-f923de4d6dce.png">

**Comment by awisnicki** [comment]
OK, looks good. Thank you!
