### ISSUE TITLE
Revisions Tab

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#220]
Please restore the "revisions" tab to the back end view of section pages. Here is where it appears on Prod:

![screen shot 2017-09-15 at 11 57 39](https://user-images.githubusercontent.com/12518623/30494313-36e733f0-9a0d-11e7-953b-0e519429aa99.png)

**Comment by nigelgbanks** [comment]
It will appear on pages that have multiple version since the site is freshly imported most pages won't show the revisions tab since there is only one version, after edits they will appear. For example on this page:

http://livingstonestage.lib.umd.edu/spectral-imaging/creating-the-1870-field-diary

**Comment by awisnicki** [comment]
OK, great. Thank you!
