### ISSUE TITLE
1871 Field Diary Link

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#224]
This is now the second instance I've found of this link being incorrect. See screen shot. In short, all instance of http://livingstonestage.lib.umd.edu/spectral-imaging/livingstones-1871-field-diary-0 need to be changed to http://livingstonestage.lib.umd.edu/spectral-imaging/livingstones-1871-field-diary (i.e., without the final zero).

![screen shot 2017-09-15 at 13 16 33](https://user-images.githubusercontent.com/12518623/30497381-46fa2eea-9a18-11e7-985f-cc574653d862.png)

**Comment by awisnicki** [comment]
I also see some instances of http://livingstonestage.lib.umd.edu/spectral-imaging/livingstones-letter-bambarre-0 but these are being correctly redirected to http://livingstonestage.lib.umd.edu/spectral-imaging/livingstones-letter-bambarre

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
OK, thank you. Once this is on prod, if I see any other instances, I can fix these myself.
