### ISSUE TITLE
Issue with Spectral Image Viewer

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#225]
I've just been using the spectral image viewer (on prod) and, on laptop at least, find that there is something wrong with the image display pane. On first visiting the page, you can drag the images around, but once you go to transcription view, then switch to a spectral image, it becomes difficult to drag the image around, and when you move the pointer onto the transcription the image still drags around. However, at a certain point it also locks and cannot be moved around and the zoom slider stops working. I'm using the trackpad rather than a mouse.

**Comment by awisnicki** [comment]
Here's the page I was looking at: http://livingstoneonline.org/islandora/search/%221871%20Field%20Diary%22%20NOT%20integrated%20NOT%20segment?access=all&limit=catalogue&view_pid=liv%3A000095&view_page=0

**Comment by nigelgbanks** [comment]
Locking issue should be sorted now, also it won't move when dragging over the transcription, but it also doesn't stop dragging if you move back over the image, we were fortunate in that the Openseadragon team just resolve this issue recently: https://github.com/openseadragon/openseadragon/pull/1133.

**Comment by awisnicki** [comment]
That is good fortune indeed. Thanks for sorting this out so fast. Looks good!
