### ISSUE TITLE
Tables with fixed widths

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#226]
This goes back to ticket #155. We need to address images in tables with fixed widths. As you've noted, there shouldn't be any use of fixed width elements anywhere on the page as it prevents responsive design. You also indicated that you would search and remove these tables and replace them with the proper html / css.

**Comment by nigelgbanks** [comment]
Should now be sorted on stage.

**Comment by awisnicki** [comment]
Yes, I've spot checked this and it looks fixed. Thank you very much. I'll also keep an eye out for this when I do a full review of the site just prior to it's going up to prod.
