### ISSUE TITLE
Questions re: Home Page

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#227]
Where does one set the order of the home page banner images? And expand or reduce the number of these image?

Where does one set the order of the logos on the home page footer? And expand or reduce the number of these logos?

**Comment by awisnicki** [comment]
Actually, it looks like I would edit all these things via the "Content" page, by narrowing the type to either "partner" or "slide" and then editing from there. Is this correct?

**Comment by nigelgbanks** [comment]
I've just changed it so it's now the same as section pages (to reduce confusion), there is now a nodequeue for both the slides and partners.

Either edit the node queue directly:

<img width="554" alt="menu" src="https://user-images.githubusercontent.com/487373/31575335-2a5e3f80-b0dc-11e7-83fd-556f1482db4d.png">

<img width="1253" alt="nodequeue" src="https://user-images.githubusercontent.com/487373/31575323-ee0a59a6-b0db-11e7-998c-5d985556eba8.png">

Or you can visit the node and add it to the queue manually:

<img width="1277" alt="content" src="https://user-images.githubusercontent.com/487373/31575326-f5cbe330-b0db-11e7-8459-28589c738159.png">


<img width="1171" alt="a" src="https://user-images.githubusercontent.com/487373/31575328-faae0d9c-b0db-11e7-984a-81ba3bbe4347.png">

**Comment by awisnicki** [comment]
OK, all looks great on this. Thank you.
