### ISSUE TITLE
Question re: Level 2 Grid and Level 3 Carousel Images

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#229]
I see that Level 2 Grid and Level 3 Carousel Images can be reviewed via the "Files" option from the Content menu. 

I also see that these images appear in the list of items in the root menu of File Browser, but I don't not see them in the page subdirectories where I would expect to see them. So, for instance, the subdirectory in File Browser for the "Livingstone Online: An Introduction" page (http://livingstonestage.lib.umd.edu/about-this-site/livingstone-online-introduction) has the two images used to illustrate that page, but does not have the tile or carousel images for this page.

Can you clarify the workflow for how I should edit, delete, add, etc. these grid and carousel images going forward?

**Comment by nigelgbanks** [comment]
These images should not be edited directly if you wish to change these images just upload / select a image a new image on the edit page for that particular section page.

Unlike the files in "Livingstone Online: An Introduction" folder and so on, these files are actually managed by Drupal.

**Comment by awisnicki** [comment]
Ok sounds good. Thanks!
