### ISSUE TITLE
MS Viewer: Side Arrows

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#23]
The arrows at the side of the viewer should be the same as appear at the sides of the other pages on the site, for instance: http://livingstonestage.lib.umd.edu/his-own-words/his-own-words-overview

**Comment by nigelgbanks** [comment]
I can do this, but it might be a bit confusing in that they arrows server different purposes, one moves pages within a document where as the other takes the user to a completely different page.

**Comment by awisnicki** [comment]
Good point. OK, let's do the following compromise:
Use the same arrows as on the other pages of the site, but invert their color (so that it's a grey arrow on a dark gray background -- same color you have now), and make them smaller that the other pages of the site (so similar size to what you have now). 
So that way they'll be continuity with the other pages, but also difference.

**Comment by nigelgbanks** [comment]
Tried inverting it and it looked pretty ugly:

<img width="802" alt="screen shot 2016-06-01 at 16 10 50" src="https://cloud.githubusercontent.com/assets/487373/15715015/dae7814c-2814-11e6-8cf4-2138c87a5da2.png">

So opted for the original look.

<img width="776" alt="screen shot 2016-06-01 at 16 21 32" src="https://cloud.githubusercontent.com/assets/487373/15715048/f0f37f72-2814-11e6-866a-0fc3a3306510.png">

**Comment by awisnicki** [comment]
Agreed. The original look looks better. However, the arrows are now are are too big. Can you send me the image for these and I'll reduce them to the appropriate size (I can figure out how to pull the arrows right off the site) or if you want to get them closer to the size of the arrows you originally had you can do that too and I'll review.

**Comment by nigelgbanks** [comment]
I scaled it to the same size as before.

**Comment by awisnicki** [comment]
And also looks good, so closing this one! Well done. :>
