### ISSUE TITLE
Spectral image viewer buttons do not match prod

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#231]
Please configure the buttons in the spectral image viewer (see image below) so that theming and behavior matches prod. It looks like this is a set of settings your forgot to carry over.
![img_7202](https://user-images.githubusercontent.com/12518623/31577522-bdeaf0ce-b0d5-11e7-9f33-83b3597fd48e.PNG)

**Comment by nigelgbanks** [comment]
Should be sorted now, bug was caused by a change in css precedence due to other recent fixes.

**Comment by awisnicki** [comment]
Unfortunately, one more theming pass needed. See screen shot.

![screen shot 2017-10-14 at 14 19 23](https://user-images.githubusercontent.com/12518623/31578646-f7cf870e-b0ea-11e7-9605-32997baf4bab.png)

**Comment by nigelgbanks** [comment]
K I've removed the responsive resizing.

**Comment by awisnicki** [comment]
Unfortunately, I don't see that anything has changed. Color dropdown still looks like the same width. See screen shot below and compare with that above. Perhaps you didn't yet push up the change?
![screen shot 2017-10-17 at 15 39 41](https://user-images.githubusercontent.com/12518623/31688289-8f4da3b4-b351-11e7-9d74-fec81d7c63f1.png)

**Comment by nigelgbanks** [comment]
Should be sorted now, needed to clear the caches.

**Comment by awisnicki** [comment]
Ah-ha! And now I know what that means ;>

Looks great. Thank you!
