### ISSUE TITLE
Questions re: LEAP-XSLT repo

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#238]
I cloned the new version of the LEAP-XSLT repo, took a quick look, and see that there are a variety of structural changes to the CSS and XSL files.

For instance, in the CSS files, whereas I might have had something like this before:

`.author`

I now see that there is a prefix across everything like this

`div.transcription.style-Bambarre-letter .author`

There are also some more substantial changes to `body` and `.div-transcription` at the beginning of the files.

For XSL, it looks like the main changes are adding new classes to the `<body>` and `<div>` elements. In the quick spot check, I didn't see anything else of significance changed.

Can you give me a quick overview of what you've done with these two sorts of files (CSS and XSL), particularly do I need to keep the CSS files in this format now or would it be enough to carry over the `body` and `.div-transcription` changes to my CSS files that are still in the old format?

**Comment by awisnicki** [comment]
I have a quick question about files and directories in the LEAP-XSLT repo. I see the following files:

leap_xslt.info
leap_xslt.module

And the following directories:

fonts
images
javascripts
stylesheets

I'm not sure what these are. I'm presuming they're coming from you, but please let me know.

**Comment by nigelgbanks** [comment]
I've added 

leap_xslt.info
leap_xslt.module

These are required to use the files in Drupal

Though these directories:

fonts
images
javascripts
stylesheets

Have always been there.

**Comment by nigelgbanks** [comment]
> Can you give me a quick overview of what you've done with these two sorts of files (CSS and XSL), particularly do I need to keep the CSS files in this format now or would it be enough to carry over the body and .div-transcription changes to my CSS files that are still in the old format?

Basically almost all elements in a style sheet need to be prefixed with:

```css
div.transcription.STYLESHEET_ID ELEMENT
```

Where STYLESHEET_ID would be something like style-Bambarre-letter this means the style will only apply to children of the element with the class `div.transcription.style-Bambarre-letter`

For the styles at the top of the file, just copy and past change the parts in all CAPS:

```css
body.non-embedded-transcription,
div.transcription-viewer-content.STYLESHEET_ID {
  background: SAME_COLOR_USED_FOR_div.transcription_Element;
}
```

This is so the parent element if larger than the child has the same background color so things do not look off.

For the xslt's the body element should have the class "non-embedded-transcription":

```xml
<body class="non-embedded-transcription">
  <xsl:apply-templates select="TEI"/>
</body>
```

And the "transcription" div should have the STYLESHEET_ID as a class as well:

```
<div class="transcription style-1870-html">
```

Thats it.

**Comment by awisnicki** [comment]
OK, great thanks for letting me know on all of this. Re those directories, in re-reviewing now I think they have to do with setting up the public facing version of this page that James previously created (http://livingstoneonline.github.io/LEAP-XSLT/), so I'll just leave them alone.

Re: XSL & CSS, great. Makes sense. Thanks for clarifying that. In terms of this change (and the others related to this):

> Basically almost all elements in a style sheet need to be prefixed with:
> 
> div.transcription.STYLESHEET_ID ELEMENT

I'm guessing this has to do with not having styling of elements in the HTML files interfere with similar elements on the pages in which these files are embedded in the site. Is that correct? I'll go ahead to keep the forward momentum going and close this ticket, but please confirm.
