### ISSUE TITLE
Tooltips issue in MS Viewer

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#240]
I've also found a small issue with tooltips in the MS viewer (also in spectral image viewer). The tooltips appear easily on mouseover, but then are very peristent and it is hard to get them off the screen.

By contrast, tooltips work fine in the multitext viewer.

**Comment by nigelgbanks** [comment]
Should be sorted now

**Comment by awisnicki** [comment]
Awesome, thank you!
