### ISSUE TITLE
NINES RDF

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#242]
I filled out the author and editor fields for all section pages this week, but when I generated the NINES RDF just now, I found that this author/editor info was not being added to the files.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Unfortunately, this one's still not working right. All names are appearing, but my name always comes out first as author, even if I'm listed second as author. When I'm listed as editor, my name comes out as author and editor:

```
		<role:AUT>Wisnicki, Adrian S.</role:AUT>
		<role:EDT>Wisnicki, Adrian S.</role:EDT>
```

In other words, it looks like my name is hard-coded to appear as author and always first, whereas it should just be putting out names as they appear, only in the fields in which they appear, i.e., if I'm only listed as editor in the back end, then I should only appear as editor in the RDF.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Unfortunately, this one is still not sorted. It's a little hard to tell what's going on, but it appears that I never come up when I'm editor and, when there is more than one instance of an author or editor field, only the first instance comes up.

**Comment by awisnicki** [comment]
You can use the fields from the following pages to compare against generated RDF, to see if all is transferring over:

http://livingstoneonline.org/in-his-own-words/field-diary-iv-overview

http://livingstoneonline.org/life-and-times/livingstone-s-posthumous-reputation

http://livingstoneonline.org/spectral-imaging/the-diary-across-hands-space-and-time-1

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Yes, looks great. Thanks for taking care of this!
