### ISSUE TITLE
Small theming issue on images

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#243]
I've come across a small theming issue on images. When two images are side by side, they look fine, but when the move to mobile version, they're piled on top of each other and on top of the caption. When in mobile, the images should each get a touch of padding below them. See screen shots.

![screen shot 2017-11-13 at 17 45 58](https://user-images.githubusercontent.com/12518623/32755450-ff1d0e42-c89a-11e7-8b5d-3cc36a71b40a.png)
![screen shot 2017-11-13 at 17 46 07](https://user-images.githubusercontent.com/12518623/32755451-ff409e66-c89a-11e7-8bad-6908e8fc968b.png)
![screen shot 2017-11-13 at 17 46 09](https://user-images.githubusercontent.com/12518623/32755452-ff5d8418-c89a-11e7-9c34-79f47f461fa7.png)

**Comment by nigelgbanks** [comment]
should be sorted now.

**Comment by awisnicki** [comment]
Yes, all sorted on this. Thank you!
