### ISSUE TITLE
Transcription Search Not Work

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#247]
I've discovered that something has become disconnected and the basic search of transcriptions on the site is not working. I haven't touched anything related to this, so I suspect it's been disconnected for a while.

![screen shot 2018-04-02 at 11 53 16](https://user-images.githubusercontent.com/12518623/38205663-fd2d364e-366c-11e8-9756-cac371297694.png)

**Comment by nigelgbanks** [comment]
Should be sorted now, seems it was introduced when renaming and reordering the fields, I forgot to check the code Drupal solr field indexes that would be changed by the change in field prefixes.
