### ISSUE TITLE
MS Viewer: Transcription / Item Details Buttons

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#27]
When "Item details" and/or "Transcription" buttons are depressed, they should somehow be highlighted. 

Text in buttons should be .85 em

Default text should say "Show edited text". When depressed, it should say, "Show unedited text".

**Comment by awisnicki** [comment]
Done on highlighting. 
Done on .85 em.
For the last, "Show edited text" v. "Show unedited text." This is more confusing that I anticipated. Can we do two buttons side by side? When the given button is depressed it turns grey, and only one or the other can be gray at one time (i.e., not both at the same time).

**Comment by awisnicki** [comment]
I'd like to expand this ticket to group three things:
1. (from previous comment): For the last, "Show edited text" v. "Show unedited text." This is more confusing that I anticipated. Can we do two buttons side by side and center them over the text? When the given button is depressed it turns grey, and only one or the other can be gray at one time (i.e., not both at the same time).
2. Would it be possible to put these on a sticky header or simply keep them permanently at the top of the transcription window so that they were easily accessible however far down the user was in the transcription? If not, then I'd like to put an empty line between the bottom of these buttons and the top of the first line of the transcription text -- i.e., the buttons should not be right on top of the transcription text.

**Comment by nigelgbanks** [comment]
Something like this where only one button is toggle-able at a time?
<img width="1266" alt="screen shot 2016-05-31 at 18 36 52" src="https://cloud.githubusercontent.com/assets/487373/15684401/da4bbe58-275e-11e6-8f59-e0f84e44d18a.png">

2-3 hours to do.

**Comment by awisnicki** [comment]
I've now done the XSLT in such a way that things that would have normally be toggled on and off with these buttons are now highlighted with various colored dotted lines and revealed via tooltip, so I think we can take this off the list. Please remove this button all together and then go ahead and close out ticket.

**Comment by nigelgbanks** [comment]
The buttons generated by the XSLT here: https://github.com/livingstoneonline/LEAP-XSLT/blob/e4f5cca431679905cc9942d5a2e0fe76ed8672c0/transcription.xsl#L52 so you can remove it with your other changes.

**Comment by awisnicki** [comment]
Excellent. I'll remove this. So closing this issue....
