### ISSUE TITLE
MS Viewer: Zoom and Move Speed

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#28]
Please slow down the speed at which the viewer zooms in and at which items move around the screen. If you provide me with the current values, I can give you preferred values.

**Comment by nigelgbanks** [comment]
The values aren't really corresponding to anything in particular (it's not a 1-100 sort of thing). But I've slowed them down quite a bit and we can always do a call after to adjust it.

**Comment by awisnicki** [comment]
OK, sounds good.

**Comment by awisnicki** [comment]
Let's adjust speed on a call later this week. I think what may be bothering me is less the speed than the fact that the image "swims" -- that it keeps moving after you push the button or stop dragging it. Is there a way to turn this swimming off?

**Comment by nigelgbanks** [comment]
Fixed weird dragging behaviour. Currently much smoother, it will however snap back to the approximate centre if you drag it toward the edges, this is a feature to prevent "losing" the image outside of the bounds of the viewer.

**Comment by awisnicki** [comment]
Let's discuss this in a call this week, the same one in which we discuss #24.

**Comment by awisnicki** [comment]
All good.
