### ISSUE TITLE
Error when trying to sync dev via github desktop

### ISSUE THREAD

**Issue by kappaluppa** [livingstoneonline/livingstoneonline#3]
Submodule Not Removed Completely
The submodule at "docker-livingstone" was removed from .gitmodules, but the folder still exists in the repository. Delete the folder, commit the change, then try again.

**Comment by nigelgbanks** [comment]
Looks like you added a sub-module in this commit:

https://github.com/livingstoneonline/livingstoneonline/commit/4e39ec2a0ba6434a560e7985ccb0d38720145fb4

Along with all of your generated credentials and some other things, I think you must have used the Github Desktop application to clone the existing repository (https://github.com/livingstoneonline/docker-livingstone) into the same folder you had this repository checked out from.

**Comment by nigelgbanks** [comment]
I removed all the bad commits from the three branches and sent out an email for everyone on how to revert back to the working setup.

**Comment by awisnicki** [comment]
Hi Nigel,
Did you meant to send this email to me? I did clone some repos onto my Github desktop application, (features, themes, docker), but that was just to follow along with updates. Each one did get its own subdirectory. I'm not making any changes, that's all Kathy.
Adrian

**Comment by nigelgbanks** [comment]
Since you're a member of the LivingstoneOnline organization in Github you'll receive email notifications whenever issues are updated or closed. 

You can change these settings under your account.

Here's a link to the site documentation: https://help.github.com/categories/notifications/
