### ISSUE TITLE
MS Viewer: Arrows and Transcription/Item Details

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#32]
Right now, when the Transcription / Item Details pages appear the arrows at the sides of the page appear below them. The arrows should appear on top of them and should be clickable.

**Comment by nigelgbanks** [comment]
If I understand correctly the arrows should only appear over the image viewer, and not over the transcription text or item details.

**Comment by awisnicki** [comment]
That's right, though I wonder if we should also put a second set on the transcription text as an alternative way to allow users to go to the next or previous page in the transcription. If that's not difficult to add, let's try that out. Otherwise, we can take this off the list.

**Comment by awisnicki** [comment]
Given that some text will be quite wide and so the arrows would float over that text, I think it's fine to take this off the list, so I'm closing this ticket.
