### ISSUE TITLE
MS Viewer: Digital Edition Text

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#34]
Please use this text for the Digital Edition section of the item details:

**Publisher:** Livingstone Online
**Directors:** Adrian S. Wisnicki, Christopher Lawrence (emeritus), Megan Ward, Anne Martin
**Project Host:** University of Maryland Libraries
**Publication Date:** 2016
**Transcription Team:** [Taken from TEI. We need to review how this is done. Should only be shown if there is a transcription.]
**Cite item (MLA):** [creators separated by semi-colons if necessary followed by period]. [title type="alternative" in quotation marks with period before closing quotation mark]. Livingstone Online. Adrian S. Wisnicki, Christopher Lawrence, Megan Ward, and Anne Martin, dirs. University of Maryland Libraries, 2016. Web. [Auto-generated access date: day/month/year in written form followed by a period, e.g. 9 May 2016].

Notes: 
1) So all fields are static, except "Transcription Team" which will be taken from the TEI (if available) and "Cite Item" which will come partly from the MODS and be partly auto-generated.
2) Here's an example of a citation:

Livingstone, David, 1813-1873. "Letter to Parents and Sisters, 29 September 1841." Livingstone Online. Adrian S. Wisnicki, Christopher Lawrence, Megan Ward, and Anne Martin, dirs. University of Maryland Libraries, 2016. Web. 9 May 2016.

**Comment by nigelgbanks** [comment]
Ready for review (although Transcription Team isn't implemented yet, we can do that as a separate ticket once we have the details about what we want to render there.)

**Comment by awisnicki** [comment]
A few small changes are still necessary:
1) Please change the Directors line to the following:
Leadership: Adrian S. Wisnicki (director), Christopher Lawrence (director emeritus), Megan Ward (associate director), Anne Martin (associate director)
2) In the Cite Item section, 
a) I asked for: [title type="alternative" in quotation marks with period before closing quotation mark] but you've put the period outside of the closing quotation mark.
b) Please put Livingstone Online in italics.

**Comment by awisnicki** [comment]
Closing this ticket, since I've combined it with #33.
