### ISSUE TITLE
MS Viewer: Tweaks to Item Details Rendering

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#35]
1) Repository field is currently showing creator
2) Image Credits should show all fields as one continuous block of text that starts on the same line as "Image Credits:"

Image Credits: Images © National Library of Scotland. Creative Commons Share-alike 2.5 UK: Scotland (https://creativecommons.org/licenses/by-nc-sa/2.5/scotland/). As relevant, © Dr. Neil Imray Livingstone Wilson. Creative Commons Attribution-NonCommercial 3.0 Unported (https://creativecommons.org/licenses/by-nc/3.0/).

3) In image credits, rather than showing the URLs (as above), could we have the foregoing Creative Commons text hyperlinked (to open in new tabs) with the URLs?

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Still wonky as follows:
1. Multiple instances of creator should be separated by a semi-colon, not comma
2. Please change "Authors" to "Creator(s)"
3. Repository field is showing Addressee plus repository.
4. Image credits field appears to be static and exactly the same for each item, whereas it should be pulled dynamically from the MODS like the other field here.

**Comment by nigelgbanks** [comment]
I can't pull the image credits from the MODS _and_ replace text with a URL as the text is **not** [regular](https://en.wikipedia.org/wiki/Regular_language). So I'm currently just pulling whats in the MODS. If you are guaranteed to have only a certain set of copyright types I could match explicitly against those (but cases in which there is a spelling mistake or some such it won't work), alternatively you could alter the data such the the links and the text that represent them by extending the `mods` to make use of the [CDL Copyright schema ](http://www.cdlib.org/groups/rmg/) for more info [MODS Documentation](https://www.loc.gov/standards/mods/userguide/accesscondition.html)

**Comment by awisnicki** [comment]
OK, I think there are two easier solutions here:
1. You could take a URL that appears in the MODS Access Condition field and simply hyperlink it. I believe that would be straightforward, no?
2. I could modify the MODS records so that the access condition field has an "a href" tag with proper URL around any item that should be hyperlinked. I just tested this out and the MODS schema seems to accept it. This change would be easy to make and appears to achieve what we need. Should I go ahead and do it?

**Comment by nigelgbanks** [comment]
I've implemented number 1. So it will appear like so:

> Images © David Livingstone Centre. Object images used by permission. May not be reproduced without the express written consent of the National Trust for Scotland, on behalf of the Scottish National Memorial to David Livingstone Trust. Images of the objects from the David Livingstone Centre are © Roddy Simpson. Creative Commons Attribution-NonCommercial 3.0 Unported (https://creativecommons.org/licenses/by-nc/3.0/).

**Comment by awisnicki** [comment]
Excellent. Looks good! Closing this issue.....
