### ISSUE TITLE
Browse by Catalogue: End of Table

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#36]
The end of the table is full of pages of empty boxes:

http://livingstonestage.lib.umd.edu/islandora/search/*%3A*?type=edismax&page=144

These should be removed.

**Comment by awisnicki** [comment]
I'm still seeing it:

http://livingstonestage.lib.umd.edu/islandora/search/*%3A*?type=edismax&page=28

This doesn't come up if I click on the link I cited in the first post in this thread. But if I start from that link, then go to, for example, page 26 of the records, then go to page 28 (the link I'm giving you here), you can see that the issue is still there.

You'll note too that by following this process ":" is also again appearing in the search box.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Yes, appears resolved. Thank you!
