### ISSUE TITLE
Browse by Catalogue: Minor modifications

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#38]
Two small things:
1. For the "Full Record" checkbox, please lower the "Full Record" text slightly so that the bottom of the text is flush with the bottom of the checkbox. (Right now it's higher)
2. When the Full Record box is checked, the table drops down a bit. It should not drop down, but rather stay where it is.

**Comment by awisnicki** [comment]
#2 is done.
For #1, please drop the text still a touch more then you can close this issue.

**Comment by nigelgbanks** [comment]
It's a bit lower now, deployed on stage & prod.

**Comment by awisnicki** [comment]
Unfortunately, the bottom of the check box and the bottom of the words "Full Record" still do not look flush. "Full Record" looks like it's higher.

Also sticking two items here, as this seems the best place for them:
1. Please alphabetize the items in the genre column in the table as you have in the creator and addressee fields.
2. Can you add a final column (i.e., all the way on the right) in the full table view called "Project ID" that would simply given the liv number from the MODS? This is the mods:identifier type='local' displayLabel='master_id'

**Comment by nigelgbanks** [comment]
> Please alphabetize the items in the genre column in the table as you have in the creator and addressee fields.

The genre column seems to be alphabetical order?

**Comment by awisnicki** [comment]
I don't think it is. Open to full view from the default landing page and take a look at the second item, for instance:

signatures (names);
books;
autographs (manuscripts);
publications

It should be in the following order:

autographs (manuscripts);
books;
publications;
signatures (names);

**Comment by nigelgbanks** [comment]
Oh I misunderstood I thought you were taking about the select field.

On Saturday, 28 May 2016, awisnicki notifications@github.com wrote:

> I don't think it is. Open to full view from the default landing page and
> take a look at the second item, for instance:
> 
> signatures (names);
> books;
> autographs (manuscripts);
> publications
> 
> It should be in the following order:
> 
> autographs (manuscripts);
> books;
> publications;
> signatures (names);
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/livingstoneonline/livingstoneonline/issues/38#issuecomment-222311214,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAdvzVTzAOW_yijr2nHZ40pbf90mlz33ks5qGFB_gaJpZM4Igmbp
> .

## 

Nigel Banks
nigel.g.banks@gmail.com

**Comment by nigelgbanks** [comment]
> In the main table, currently only one genre appears in the genre field, but there can be up to FOUR, so all these should be **listed as relevant**, but separated by a ;  So if the MODS record says:

https://docs.google.com/document/d/14lKUnmSN45E5uCBDbwGdVQoadR3zseSlo4oy5hpnYz8/edit

Just to confirm we want to change genre fields within an single cell to be sorted by Alphanumerically?

**Comment by awisnicki** [comment]
Odd! I thought I answered this one. Yes, that's correct alphanumerically, just like currently happens in the creator and addressee fields.

**Comment by nigelgbanks** [comment]
K that'll have to wait a bit as I need to rebuild to the solr index to do so.

**Comment by nigelgbanks** [comment]
Index has been rebuilt.

**Comment by awisnicki** [comment]
This looks good. However, please put each individual genre on its own line, per the model of the creator/addressee columns.

Separately, I'll just throw this small bit in here rather than creating a new ticket, but I noticed when reviewing this that in the viewer, in the Item Details section, when there are two creators, they are separated by a comma rather than semi-colon. Please make it semi-colon. Example:
http://livingstonestage.lib.umd.edu/islandora/search?full_record=1&sort=desc&order=Title&view_pid=liv%3A000214&view_page=0

**Comment by nigelgbanks** [comment]
Fixed as for

> Separately, I'll just throw this small bit in here rather than creating a new ticket, but I noticed when reviewing this that in the viewer, in the Item Details section, when there are two creators, they are separated by a comma rather than semi-colon. Please make it semi-colon. Example:
> http://livingstonestage.lib.umd.edu/islandora/search?full_record=1&sort=desc&order=Title&view_pid=liv%3A000214&view_page=0

It's now in it's own ticket https://github.com/livingstoneonline/livingstoneonline/issues/50, don't worry about creating small tickets, small single purpose tickets are easier to deal with rather than large tickets with unrelated issues.

**Comment by awisnicki** [comment]
Genre, looks good. I'm closing this one! Also, duly noted on small tickets. I'll do that going forward.
