### ISSUE TITLE
Browse by Catalogue: Change title

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#39]
Please change the title of this page (http://livingstoneonline.org/islandora/search), including the title that appears on the browser tab, to "Browse by Digital Catalogue Record" (i.e., I'd like to substitute the word "Digital" for the word "Standard"). Normally, I would do this through Drupal, but even though I've changed the title there, it is not changing on the page itself.

**Comment by awisnicki** [comment]
Looks good. Thank you! I'm closing this thread but can you tell me briefly why I wasn't able to change this title myself?

**Comment by nigelgbanks** [comment]
It was/is hard-coded in the theme here:

https://github.com/livingstoneonline/livingstone_online_theme/blob/dev/templates/html--islandora--search.tpl.php#L6

On Tue, May 31, 2016 at 7:52 PM, awisnicki notifications@github.com wrote:

> Closed #39
> https://github.com/livingstoneonline/livingstoneonline/issues/39.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/livingstoneonline/livingstoneonline/issues/39#event-677445712,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAdvzem-hT-eIMPBa6hCytHRxhY3ckaRks5qHINXgaJpZM4Ij12W
> .

## 

Nigel Banks
nigel.g.banks@gmail.com
