### ISSUE TITLE
Browse by Catalogue: Hide Facet count on selected facet

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#40]
When the user selects a facet, remove the facet count from it's display.

**Comment by awisnicki** [comment]
Note: it would be enough truncate the display on date so only the year show and the facet count doesn't appear. It is useful to have the count appear with other facets, even after you've selected one of them

**Comment by awisnicki** [comment]
This appears to be fixed, even though you haven't updated this ticket. If not correct, the please reopen this ticket.
