### ISSUE TITLE
MS Viewer: Mobile support for the header

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#44]

**Comment by nigelgbanks** [comment]
Partially done, not 100% but is functional.

**Comment by awisnicki** [comment]
OK, thank you for this update. So should I be looking at anything (and if so, what?) or should I wait on you to bring this closer to the end?

**Comment by nigelgbanks** [comment]
Wait for now, at the moment it's functional in that nothing is hidden and it resizes appropriately, but the margins between icon isn't ready yet; this also ties into issues/24.

**Comment by nigelgbanks** [comment]
Pretty solid now for responsive resolutions, I paid special attention to iPad in landscape mode, so the bar fits on the entire line. With large screens it should look good as well.

**Comment by awisnicki** [comment]
As noted in #24, we'll come back to review this after sorting out #24.

**Comment by nigelgbanks** [comment]
Closing this ticket to combined mobile feedback to a single ticket => #55
