### ISSUE TITLE
MS Viewer: Image numbering in transcription

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#45]
1) The image identification info for each page of the transcription is currently bold, centered, has a semi-colon after the word "image" and has an empty line below it. Please change this as follows:

rend left
no bold
in square brackets
remove semi-colon
empty line above rather than below

2) Please remove the black horizontal line that appears between pages of the transcription.

---

So, in other words, going from one page of the transcription to the next would look like the following:

That, the scriptures of the old and new Testaments, are a revelation of the will
of god to fallen man, this being attested by such evidence as no one with an unbiased 
mind can resist. That they contain a perfect rule of faith and practice. "All

[Image 0003]
scripture being given by inspiration of god, and profitable for doctrines for
reproof, for correction, for instruction in righteousness," From these we learn that 

---

Also a question, would it be difficult to hyperlink the [Image 0003 text] to the relevant image so that when you clicked on the hyperlinked text in the transcription it would call up the relevant image?

**Comment by awisnicki** [comment]
My changes to the XSLT have resolved all of this and so only my question at the end needs to be addressed:

Would it be difficult to hyperlink the [Image 0003 text] to the relevant image so that when you clicked on the hyperlinked text in the transcription it would call up the relevant image?

It's possible, I might be able to set this up via the XSLT myself.

**Comment by nigelgbanks** [comment]
It's not possible via the XSLT alone, as the XSLT won't be aware of the url parameters so any added links are like to remove the users facets (Genre, etc). It can be achieved via javascript though.

**Comment by awisnicki** [comment]
How much work would this entail?

**Comment by nigelgbanks** [comment]
1-2 hours

**Comment by awisnicki** [comment]
Could we go ahead and do this then? I tried to take a few things off the list/close out some tickets to compensate for the added time here.

**Comment by awisnicki** [comment]
Looks good. Thank you! I'll also change the CSS to make it obvious that this is a link.
