### ISSUE TITLE
MS Viewer: Slide Out Menu

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#47]
The slide out menu which is accessed from the icon in the upper left-hand corner is wonky. Please compare to other pages on the site.

**Comment by awisnicki** [comment]
This looks good except the height of the colored boxes is taller than elsewhere. Please double-check the height against the other pages of the site. Also, the social media icons which previously appeared here (four in a row, on one line -- on all pages of the site) are missing. I don't know if this is due to something you or Kathy did, but you might check with her.

**Comment by nigelgbanks** [comment]
I believe Kathy removed the icon's but I can check the heights.

**Comment by awisnicki** [comment]
I think we can ignore the icon issue. It's there on prod, just not on stage. I assume the icons will just show up in the right place when this (the slide out on the MS viewer) gets to prod? If so, then that just leaves the height issue.

**Comment by nigelgbanks** [comment]
Changed the height and deployed to stage.

**Comment by awisnicki** [comment]
Looks good. Thank you!
