### ISSUE TITLE
MS Viewer: Image padding

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#48]
Images, when they first appear in the viewer, need some padding at the bottom so that the bottom of the image is not touching the bottom of the browser by default. This was fine before but seems to have been undone by the remove of the thumbnail strip. The padding below the image should be the same as the padding above (which currently looks good).

**Comment by awisnicki** [comment]
Still not quite right. It seems like you made it smaller.

 Open any image, click "Item Details," then close "Item Details" and you will see that the padding has changed and is now slightly larger above and below. The images should also by default open with this amount of padding.

**Comment by nigelgbanks** [comment]
I've made the margin a bit larger at the start, we can't make it exactly the same as when the item details is showing, as the image will dynamically zoom to keep it's proportions.

**Comment by awisnicki** [comment]
Perfect, thank you! Closing this issue.
