### ISSUE TITLE
Browse by Catalogue: Column Sort Order

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#49]
Let's discuss this in a call this week.

**Comment by awisnicki** [comment]
OK, actually this is simple enough:

I'd like the main sort to be according to ISO date (as is).
Then the textual date, the first person in the Creator(s) column, then the Title.

So, in other words, sorting by these four columns in this order:

ISO date, textual date, first person in Creator(s), Title

Also, while you're looking a this, could you widen the "Other Version(s)" column by half. So, if it's 1 now, make it 1.5, please.

**Comment by nigelgbanks** [comment]
ISO date, textual date, first person in Creator(s), Title
The first sort field ISO date will change with the user selected column, the others will remain fixed and applied regardless of the sort field the user chooses.

**Comment by nigelgbanks** [comment]
Rebuilding the solr index now.

**Comment by awisnicki** [comment]
Well done!
