### ISSUE TITLE
Browse by Catalogue: Sorting by Hidden Fields

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#5]
If you sort on a field that is not displayed by default (one that only appears when full record is selected), the order of the columns does not display correctly on the page refresh.

Nigel: Has to do with the split table issue (header is a separate table, I think this should be done from scratch, will take awhile though).

Will be done as part of the re-write of the Browse by Catalogue page.

**Comment by nigelgbanks** [comment]
Deployed to stage, ready for review.

**Comment by awisnicki** [comment]
This appears to be resolved. Thank you for your work on this!
