### ISSUE TITLE
Item Details 

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#50]
> Separately, I'll just throw this small bit in here rather than creating a new ticket, but I noticed when reviewing this that in the viewer, in the Item Details section, when there are two creators, they are separated by a comma rather than semi-colon. Please make it semi-colon. Example:
> http://livingstonestage.lib.umd.edu/islandora/search?full_record=1&sort=desc&order=Title&view_pid=liv%3A000214&view_page=0

**Comment by awisnicki** [comment]
Looks good. Thank you!

**Comment by awisnicki** [comment]
Sorry, I have to reopen this ticket. Take a look at this item:
http://livingstonestage.lib.umd.edu/islandora/search?f[]=repository_ms%3A%22National+Library+of+Scotland%22&f[]=genre_ms%3A%22color+slides%22&view_pid=liv%3A014073&view_page=0

And others like it, here: 
http://livingstonestage.lib.umd.edu/islandora/search?f[]=repository_ms%3A%22National+Library+of+Scotland%22&f[]=genre_ms%3A%22color+slides%22

Item details should include John Murray _and_ Unknown Creator but the Unknown Creator is missing.

(Also, I don't know if this is just a temporary glitch, but the first two items available the Browse link above are not coming up in the viewer).

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
OK, looks good re: Unknown Creator, so I'm closing this. The first two items are still not coming up, however: 

http://livingstonestage.lib.umd.edu/islandora/search?f[]=repository_ms%3A%22National+Library+of+Scotland%22&f[]=genre_ms%3A%22color+slides%22&view_pid=liv%3A014071&view_page=0

http://livingstonestage.lib.umd.edu/islandora/search?f[]=repository_ms%3A%22National+Library+of+Scotland%22&f[]=genre_ms%3A%22color+slides%22&view_pid=liv%3A014069&view_page=0

**Comment by nigelgbanks** [comment]
Fixed a small mathy issue with openseadragon (only affected really large images) they both should appear at all zoom levels now.
