### ISSUE TITLE
Browse by Catalogue: Access Dropdown

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#58]
In the Access dropdown, after "View & Download," we now need an option for sorting "Restricted" items. If you think this will be a quick job, no need to provide a time estimate before proceeding.

Also note that currently, if you select "Download" from the dropdown, the "Restricted" items also come up although, obviously, you can't download these. This might be considered a buy and/or require a new ticket -- if so, please open one.

**Comment by nigelgbanks** [comment]
> In the Access dropdown, after "View & Download," we now need an option for sorting "Restricted" items. If you think this will be a quick job, no need to provide a time estimate before proceeding.

I don't think this will take more than an hour.

> Also note that currently, if you select "Download" from the dropdown, the "Restricted" items also come up although, obviously, you can't download these. This might be considered a buy and/or require a new ticket -- if so, please open one.

This is bug (might be a regression from work I did 3 weeks ago) and should have been covered under existing functionality so I'm moving it to a new ticket (time put into it won't go under general consulting).

**Comment by awisnicki** [comment]
OK, then feel free to take both these things forward.

**Comment by awisnicki** [comment]
All looks good. Thank you!
