### ISSUE TITLE
Browse by Catalogue: Search limiting

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#59]
1) Please make the Catalogue search box white and please fill it with the following text:
"Search full catalogue and transcriptions"
If this is slightly too long, you can replace "and" with "&"

2) Please add a new dropdown, right below the search bar (and so right above the Full Record box) that says "Limit search". The options, once this is selected, should be: 
Search catalogue only
Search transcriptions only
Search catalogue & transcriptions

**Comment by nigelgbanks** [comment]
Item 1) is pretty straight forward and will be less than 15 mins. 2) will be in the range of about 2 hrs.

**Comment by awisnicki** [comment]
OK, please feel free to take both forward.

**Comment by nigelgbanks** [comment]
"Search full catalogue and transcriptions" doesn't fit, "Search full catalogue & transcriptions" does at some resolutions. ~~Also I think it's worth noting that transcriptions are not searched from this field (they used to, but at one point you asked to have it only search the columns being displayed). So perhaps "Search full catalogue" would work best?~~ Never mind the above point 2) indicates that functionality should be added.

**Comment by awisnicki** [comment]
OK, how about "Search catalogue & transcriptions" (without the "full") or "Search catalogue / transcriptions" (note the space before an after the slash). As a last resort, we could do "Search digital catalogue" (just like the page title) and we'd assume this encompassed both catalogue and transcriptions

**Comment by nigelgbanks** [comment]
Only "Search digital catalogue" fit for all resolutions.

**Comment by awisnicki** [comment]
Functioning looks good, thank you! 
1) Please increase the space between the search box and the new search dropdown so that this space is the same as between the other dropdowns (currently it's a bit too narrow).
2) Please slightly close up the space between the new search dropdown and and the "Full Record" checkbox line. The space is slightly too big now. It should be the same as bewteen the Full Record line and the Date dropdowns.

**Comment by nigelgbanks** [comment]
Ready for re-review.

**Comment by awisnicki** [comment]
Looks good. Push to prod. Thanks!
