### ISSUE TITLE
Browse by Catalogue: Text in Table Headers

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#6]
Please adjust the headers on the table as follows:

Change “Date” to “Date(s)”
Change “Creator” to “Creator(s)”
Change “Addressee” to “Addressee(s)”
Change “Place Created” to “Place(s) Created”
Change “Genre” to “Genre(s)”
Change “Other Versions” to “Other Version(s)”

Nigel: Using parenthesis in title fields causes the search module to fail to return results, outstanding bug in core islandora it would seem. Can be sorted out when rebuilding this page.

**Comment by nigelgbanks** [comment]
Deployed to stage, ready for review.

**Comment by awisnicki** [comment]
Looks good. Thank you!
