### ISSUE TITLE
Manuscript Viewer: Download current item

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#60]
On the "Item Details" page, in the "Digital Edition" section, after the "Date" line, please put a new line that says:

Download item: [down-arrow] [size of item]

So, in other words, the last two things should look just like they do in the catalogue.

**Comment by awisnicki** [comment]
Looks good, except you put it after the Date in the "Item Details" section, but you'll note above that I said it should go after the Date in the "Digital Edition" section.

**Comment by nigelgbanks** [comment]
Whoops, it's on stage now.

**Comment by awisnicki** [comment]
Looks great. Push to prod. Thanks!
