### ISSUE TITLE
Browse by Catalogue: Page Refresh

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#61]
When I'm at the bottom of a given page and I select a number to take me to the next page, the page should automatically go to the top. 

Note: We're also planning to do lazy load on this page, which would eliminate the need for this, so please advise whether we should consider skipping this all together (or, alternately, maybe it's time to put some time estimates on the items in issue #10 -- i.e., lazy load and sticky header?).

**Comment by nigelgbanks** [comment]
Your right with issue #10 it will make this change redundant, that being said; I likely can implement this less than 1 hour. I'll have to do some research on the lazy loading header there isn't an off the self solution I know of that works with Drupal tables.

**Comment by awisnicki** [comment]
Ok, either implementing the temporary solution (since it will take little time) or, alternately, going to the work in issue #10 would be OK with me. Please go ahead and look into all of this and let me know how you think best to proceed. Happy to discuss options with you if necessary. Just let me know.

**Comment by nigelgbanks** [comment]
It was faster to implement this than to scope out #10, it's ready for review.

**Comment by awisnicki** [comment]
Looks good on Safari & Chrome but doesn't work on Firefox.

**Comment by nigelgbanks** [comment]
Good catch, odd bug that. The fix is on stage.

**Comment by awisnicki** [comment]
Fixed!
