### ISSUE TITLE
Browse by Catalogue: Access Column Width

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#62]
On prod, the access column width is correct on Chrome for default view. In the majority of cases, the camera icon, the download icon, and the download size all appear on one line and do not wrap to a second line.

However, the access column in the full record view on Chrome and both the default and full record views on Firefox are too narrow. You might also check other browsers on this.

See attached screen shots. 
![screen shot 2016-06-17 at 8 23 53](https://cloud.githubusercontent.com/assets/12518623/16151959/187e9d9a-3465-11e6-8989-c04a81e7ef7c.png)
![screen shot 2016-06-17 at 8 23 56](https://cloud.githubusercontent.com/assets/12518623/16151957/18796fc8-3465-11e6-9245-577388fa3f86.png)
![screen shot 2016-06-17 at 8 24 04](https://cloud.githubusercontent.com/assets/12518623/16151958/187e034e-3465-11e6-8185-2ce4bfa8826c.png)
![screen shot 2016-06-17 at 8 25 31](https://cloud.githubusercontent.com/assets/12518623/16151960/18800522-3465-11e6-94ba-71c17b8a2809.png)

**Comment by awisnicki** [comment]
This issue has partly resolved on the landing pages, but when opened to Full Record, the issue persists. In short, we need to set the Access column at a fixed width, just wide enough that it accommodates  camera/arrows/download size in one row, and this width should be fixed in short and full view on all versions of the site (Desktop, iPad, iPhone, etc).

**Comment by nigelgbanks** [comment]
Should be good now, you'll need to clear your cache when viewing so you don't get the old css.

**Comment by awisnicki** [comment]
Yes, looks good. Thanks for sorting this out. Closing.....
