### ISSUE TITLE
Browse by Catalgoue: Link in Other Verisons Column

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#64]
On Prod, some of the URLs in the Other Versions column as coming up as URLs rather than as the word "link". Take a look here for example:

http://livingstone.lib.umd.edu/islandora/search?f%5B%5D=dateRangeYear_mi%3A%221873%22&full_record=1

**Comment by awisnicki** [comment]
The examples on the page I gave above appear to have resolved themselves, but there are still other examples where the issue persists:

Top few records:
http://livingstone.lib.umd.edu/islandora/search?full_record=1&order=Other+Version%28s%29&page=27

Random examples on this page:
http://livingstone.lib.umd.edu/islandora/search?full_record=1&order=Other+Version%28s%29&page=26

etc.

Also see the column on this page (where it actually runs out of the box): 
http://livingstone.lib.umd.edu/islandora/search?f%5B%5D=genre_ms%3A%22lantern+slides%22&full_record=1

**Comment by nigelgbanks** [comment]
I can't seem to reproduce it for any of the links.

**Comment by awisnicki** [comment]
OK, oddly when you link directly to the URLs I provided above, the issue is fixed. However, if you start at the default Catalogue landing page then, for example, narrow by genre to "lantern slides", then look at Other Versions, you'll see the issue. See screen shot. I'm doing this in Firefox.
![screen shot 2016-06-20 at 14 10 24](https://cloud.githubusercontent.com/assets/12518623/16207054/e3d375fa-36f0-11e6-83d1-906aca6668f1.png)

**Comment by nigelgbanks** [comment]
Fixed

**Comment by awisnicki** [comment]
And indeed this looks fixed too. Thanks as well. One more close.
