### ISSUE TITLE
Manuscript Content Type: Geo-coordinates

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#66]
Geo-coordinates (mods:coordinates) need to be included in this new content type as they will be needed for the Browse by Geolocation page.

**Comment by awisnicki** [comment]
It looks like it might not be a bad idea to also add the ISO date and alternate title fields.

**Comment by nigelgbanks** [comment]
ISO date is already covered in **Date Range Start** and **Date Range End** respectively for the other fields.
- mods:coordinates
- mods:titleInfo[@type="alternative"]/mods:title

We'll have to rebuild the solr index.

**Comment by nigelgbanks** [comment]
Solr index has been rebuild and content has been updated on stage.

**Comment by awisnicki** [comment]
Alternative title looks good. 

Coordinates sometimes has two or three sets of coordinates, but in all cases I see only one displayed. It would be good for each set to be displayed and separated by a ;

Also, in looking at the listing of things for the manuscript content type, I see that alternative title and coordinates appear all the way at the end of the list (see screen shot)
![screen shot 2016-07-11 at 21 01 41](https://cloud.githubusercontent.com/assets/12518623/16743021/b0a31544-47aa-11e6-80fb-bdf833301152.png)

It would be better (and more logical) to have them appear in the order in which they appear in the MODS record itself, so alternative title would appear right after title, and coordinates would appear right after place(s) created.

**Comment by nigelgbanks** [comment]
> Coordinates sometimes has two or three sets of coordinates, but in all cases I see only one displayed. It would be good for each set to be displayed and separated by a ;

I've created a multi-value field to hold them rather than putting them all into a single one, as it's more likely to work with Drupal contrib modules.

> Also, in looking at the listing of things for the manuscript content type, I see that alternative title and coordinates appear all the way at the end of the list (see screen shot)
> 
> It would be better (and more logical) to have them appear in the order in which they appear in the MODS record itself, so alternative title would appear right after title, and coordinates would appear right after place(s) created.

The fields are never shown to end users in this way, so the order isn't of any particular importance. That being said you can set the ordering to whatever you like:

http://livingstonestage.lib.umd.edu/admin/structure/types/manage/manuscript/fields

<img width="1244" alt="fields" src="https://cloud.githubusercontent.com/assets/487373/16835251/b441c4dc-49af-11e6-8144-ad9b658ff9d6.png">

**Comment by nigelgbanks** [comment]
Currently rebuilding solr index.

**Comment by awisnicki** [comment]
Oddly the link above does not work for me (I am logged in) and I can't otherwise get to the page shown in your screen shot where the various tabs appear in the upper right.
![screen shot 2016-07-14 at 21 55 00](https://cloud.githubusercontent.com/assets/12518623/16853958/1d618f56-4a0f-11e6-85ec-557b3e00673a.png)

**Comment by nigelgbanks** [comment]
Should work for you now, just had to add permissions though the interface.

**Comment by awisnicki** [comment]
Looks good. Thank you!
