### ISSUE TITLE
Pushing XSLT

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#68]
I've successfully pushed updated versions of transcription.xsl to dev, stage, and prod, but despite a number of attempts on my part prod is not using the new file. I'm not sure what I've done wrong as I've followed exactly the same procedure for stage and there the file is being recognized and is working just fine.

**Comment by nigelgbanks** [comment]
It was my mistake the passcode for automated deployment I was using for stage and production was different (a copy paste error). Automated deployment for production should now be working. I'm currently testing to make sure and will close the ticket after the build completes and deploys.

**Comment by nigelgbanks** [comment]
Looks like all is well now.
