### ISSUE TITLE
Site set-up documentation

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#69]
We need a high-level overview (circa 1 paragraph) of the overall configuration and set up of the site (using Docker, etc.) for this page: http://livingstone.lib.umd.edu/behind-scenes/practices-standards-and-arrangements Let's discuss just what this paragraph would cover.

**Comment by nigelgbanks** [comment]
I imagine we can re-use use much of the documentation from the Git Repo?

https://github.com/livingstoneonline/livingstoneonline#livingstone-online
https://github.com/livingstoneonline/livingstoneonline/tree/master/docs

**Comment by awisnicki** [comment]
Yes, absolutely, we can reuse the documentation and even point to it from the website page I've cited. On the website page itself, however, in keeping with the level of overview that is provided for the different aspects of the project, we need one paragraph to provide the high level description. It'd be great if you could put this together, since you're most conversant in the configuration. I think the paragraph would best appear in the "Hosting and Backup Arrangements" section, would be placed between the "Development Access" and "Site Versions" sections, and might be called "Site setup." However, feel free to offer recommendations on what it might be called and where it might be placed.

**Comment by nigelgbanks** [comment]
How about this?

# Site Setup

Livingstone Online is built and deployed using a number of different tools. At the heart of the system we use [Docker](https://www.docker.com/) for deployment of code and dependencies, and [Git](https://git-scm.com/) for the storing / managing code and configuration. We have a number of [Github Repositories](https://github.com/livingstoneonline) where we share our code and configuration. These repositories fall into three categories:
1. Docker Related (Builds Docker image(s) that are deployed to the server: prefixed with _docker-_).
2. Code Related (Code used by the site, to implement functionality: prefixed with _livingstone_online__)
3. Unrelated (Not related to site setup)

Docker images are build automatically when changes are made to the repositories identified above. This is performed by the [Docker Hub service](hub.docker.com/r/livingstoneonline). After Docker images are built they are automatically deployed by the [auto-deploy](https://github.com/livingstoneonline/docker-auto-deploy) application running on the sites server.

If you interested you can read more [here](https://github.com/livingstoneonline/livingstoneonline#livingstone-online)

**Comment by awisnicki** [comment]
Perfect, thanks! Added to the site.
