### ISSUE TITLE
Sitewide Search: Non-viewable items

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#71]
In the specs for sitewide search you have: 

"To have the Sitewide Search link back to the appropriate page for Manuscript items we’ll be using Drupal Node Redirects. This will rewrite the URLs for matching manuscript items such that it will take the user to Browse by Catalogue page, and display the Manuscript in the viewer when appropriate. Nonviewable Manuscripts will still link to the Browse by Catalogue page, but they will not launch the Manuscript viewer."

However, it appears that nonviewable items are in fact launching the viewer and showing the "restricted image" text. Take a look at this example:

http://livingstoneonline.org/search/node/james%20gray

**Comment by awisnicki** [comment]
Also, this is now working in views, according to Kathy. She tried constructing the correct url in the view but the PID in the content is delivered with an underscore, i.e., liv_0122025, and the url wants a colon, i.e., liv%3A0122025
(http://livingstonestage.lib.umd.edu/islandora/search/%2522liv:012025%2522?view_pid=liv:012025)

**Comment by nigelgbanks** [comment]
This has been resolved by adding a few new fields to the Drupal nodes:
- Viewable
- Hidden
- Downloadable

> using Drupal Node Redirects

The implementation for this is different than from the original description as Drupal redirects can't handle this kind of logic (generating different urls based on the presence of boolean: yes or no, values). It's now implemented as a theme function override.

I'm currently re-importing the nodes so it's not ready for testing quite yet though.

> Also, this is now working in views, according to Kathy. She tried constructing the correct url in the view but the PID in the content is delivered with an underscore, i.e., liv_0122025, and the url wants a colon, i.e., liv%3A0122025

I'm not sure I understand, is this for the timeline? In which case there is a field "PID" which contains the semicolon.

**Comment by nigelgbanks** [comment]
Re-index has completed and it's ready for review.

**Comment by awisnicki** [comment]
It looks like this works now as expected. I tested items that are viewable, downloadable only, restricted, and not viewable (because we don't have images), and all came up as expected. Kathy's question has also bee resolved so I'm closing this ticket. Thanks very much.
