### ISSUE TITLE
Restricted items showing when "Download" access view is selected in Catalogue.

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#72]
If you select "Download" from the dropdown, the "Restricted" items also come up although, obviously, you can't download these.

**Comment by awisnicki** [comment]
Looks good. However, in the Access dropdown, could you make the order of the items as follows:

View
Download
View & download [note the lower-case "d"]
Restricted
No access available

**Comment by nigelgbanks** [comment]
Changes on stage.

**Comment by awisnicki** [comment]
Looks good. Push to prod. Thanks!
