### ISSUE TITLE
Browse by Catalogue: Two small tweaks

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#73]
1) When the Catalogue first opens, on the "From" and "To" dropdowns, please put those words slightly to the left otherwise with the addition of the arrows, as the screen now narrows, the down arrows start to run onto those words. This is only necessary until those two dropdowns drop to another line at which point the issue is gone and "From" and "To" can be put back to the right place.

2) Since we now have the "Search catalogue" etc dropdown, I think we can remove the text in the search box itself, so please do so.

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks good on both. Thank you!
