### ISSUE TITLE
Issue on Prod: Level 3 Title Disappearing

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#75]
This is the same issue that came up before. The title on level 3 pages is visible, but if you click a link that's anchored to a place lower down on the page, then scroll back up, the title is gone. 

You of course got this close to working, it was fine, then I noticed the other day that the issue had returned. I went into the back end, fixed it exactly as you did (oddly the setting had changed since you set it up correctly), but this time changing the settings didn't work.

This doesn't have to work perfectly -- if, say, the title simply moves closer to the carousel that will be OK -- but the title can't be disappearing as now.

![screen shot 2016-08-15 at 16 09 32](https://cloud.githubusercontent.com/assets/12518623/17679952/695dab12-6303-11e6-881d-392050843a38.png)
![screen shot 2016-08-15 at 16 09 38](https://cloud.githubusercontent.com/assets/12518623/17679951/69598ee2-6303-11e6-9d1f-7707893f62fd.png)

**Comment by awisnicki** [comment]
Looks good! It looks like we're back to the original solution, which was not 100% but does the trick. Is that right? Let me know in case this issue comes up again.

**Comment by nigelgbanks** [comment]
Yup same solution as before, it came back because it was in one of the features which got reapplied (reintroducing the issue again). I've removed it from the feature so it shouldn't crop up again.

**Comment by awisnicki** [comment]
Nigel, could you fix this issue on stage. It's cropped up there. Please don't just copy down the prod database to stage as we're in the process of developing new content in stage so we don't want that overwritten.

**Comment by nigelgbanks** [comment]
I can't seem to reproduce it?
