### ISSUE TITLE
Browse by Catalogue: Add Facet

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#77]
Could we add a facet on the left side of the page, that would appear below the "Search catalogue only" facet and that would have the following options:

Show all items
Items with images only
Items with images & transcriptions

Note the options here would need to be coordinated with the ""Search Catalogue Only" facet, so that if someone selected "Search transcriptions only" from there, this new facet would have to change to "Items with images & transcriptions" and the other two options would be gone. There might be other such coordinations to be made, but I can't think of any just now.

**Comment by nigelgbanks** [comment]
Adding this facet would conflict with the other facets, so instead I've altered the existing facet on stage to support this use case:

![usecase](https://cloud.githubusercontent.com/assets/487373/17978780/8c6017fa-6aef-11e6-8eeb-21760d16b4cb.png)

This add's the following options to the access facet:
- View (any)
- View (w/ Transcription)
- View (w/o Transcription)
- View (any) & download

These can be used much in the same way as what was there before.

**Comment by awisnicki** [comment]
This looks good and I like this way of tackling it. Please modify slightly further so that we have all the following options:

View (any)
View (items with transcriptions)
View (items without transcriptions)
Download (any)
Download (items with transcriptions)
Download (items without transcriptions)
View & download (any)
View & download (items with transcriptions)
View & download (items without transcriptions)
Restricted
No access available

Hopefully, all those text variants will fit on the line. If not, you can got back to using w/ and w/o to see if it helps. This way all options are covered. Also note that only the first word is ever capitalized.

**Comment by nigelgbanks** [comment]
Hmm seems to only fit (and not 100% but close enough if I drop the "**items**" and use the abbreviated forms for with/without).

**Comment by awisnicki** [comment]
This looks good and you can push to prod, but let me ask a question: what about dropping the parenthesis (and restoring item) as in the following:

View (any) [leave this one as is]
View items w/ transcriptions
View items w/o transcriptions
etc.

It seems to me that if you tested this in the longest line only you'd know whether it worked. 

If you do go with this, then you should probably make it "Restricted items" also.

If not, the way you've resolved it is fine and you can close this ticket.

**Comment by nigelgbanks** [comment]
Still a bit too long:

![screen shot 2016-09-01 at 20 54 49](https://cloud.githubusercontent.com/assets/487373/18182115/69f7f57e-7086-11e6-88e6-aba4ce6caba0.png)

**Comment by awisnicki** [comment]
By the way, could you change the text in the "Access" dropdown so it actually says "Access options"

**Comment by awisnicki** [comment]
Reopening this, since the one minor mod is still needed.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Indeed it is. Thank you!
