### ISSUE TITLE
Browse by Catalogue: Tooltip

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#78]
When there is no transcription for an item in the Manuscript Viewer, could we add a tooltip to the transcription button that says "There is no transcription available for this item."

On mobile, could this be made to pop up as a text box when someone attempted to click on the button?

![screen shot 2016-08-15 at 16 51 26](https://cloud.githubusercontent.com/assets/12518623/17681021/d25113de-6308-11e6-8404-94cd11ad535f.png)

**Comment by nigelgbanks** [comment]
Let me know if you want the colours changed, etc.

**Comment by awisnicki** [comment]
Could you make it so that the font size in the tooltip is the same size as the font on the transcription/item details buttons? 

Also is it possible to have the tooltip appear below the transcription button rather than on top of it?

In terms of text and background color, let's actually make the text black and the background color be the same color as it is now for the transcription/item details buttons

**Comment by awisnicki** [comment]
Please change the top on on this to 43px (currently it's 50px) and we can close it out.

**Comment by nigelgbanks** [comment]
Change deployed to both stage and prod.
