### ISSUE TITLE
Browse by Catalogue: Wonky Table Header

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#8]
Rebuild the table so that the header is not wonky, etc. (Nigel, you noted that you would confirm with Kathy first.)

Probably around 8-12 hours (includes issues above where mentioned)

**Comment by nigelgbanks** [comment]
Deployed to stage, ready for review.

**Comment by awisnicki** [comment]
Appears to be resolved. Thank you!
