### ISSUE TITLE
Search Widget

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#80]
Here are the options that I suggest for the widget:

Search web pages
Search digital catalogue
Search transcriptions

So take out the "only." Replace the circle & dot with a box & checkmark. When you first click in the search bar, the dropdown appears and all three options are checked by default. If users want to narrow their search, they can then uncheck one or more of the boxes, etc.

In terms of theming, a ) I'd like the the dropdown from the Browse Collection button to match the search widget and b) I'd like to make a few changes to the Search Widget.
## Browse Collection dropdown theming

1) border-radius: 8px;
2) border: 1px solid rgb(208, 208, 208);
3) anything else needed to get it to look like the search widget dropdown (it's possible nothing else is needed)

Search Widget dropdown theming
1) Put a little space to the right of the check boxes, so there's a little space between the check boxes and the text to the right
2) margin-top: 32px;  [so that the dropdown appears right below the search box]
3) font-size: 0.85em;  [so that the text sizes matches that in the Browse Collection dropdown]
4) padding left: 1.5em [so that the text is slightly more centered in the dropdown]

**Comment by nigelgbanks** [comment]
Used a different padding, as the margin added to the checkboxes affected alignment, now the text should align with the text in the search box when empty.

**Comment by awisnicki** [comment]
This looks fantastic! Thank you. Just one quick small issue. The font inside of the search widget looks different from that inside of the Browse Collection dropdown. 1) Looks like different fonts and 2) Browse collection font is gray (or slightly muted black). 

I prefer what's on the Browse Collection button re: font. Could you make sure the search widget matches that?

**Comment by nigelgbanks** [comment]
Should be the same color and size, now deployed to both stage and prod.

**Comment by awisnicki** [comment]
Looks good, but appears not to be present on any of the level 3 pages. Also not working well in the manuscript viewer.

Only levels 1 (home page) and 2 (tiles pages) look OK.

**Comment by nigelgbanks** [comment]
It's deployed to stage / prod now.

**Comment by awisnicki** [comment]
Resolved. Thank you very much.
