### ISSUE TITLE
Timeline Image Size

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#83]
The images in the timeline are now indeed 100px on longest edge (so updated), but they're still showing up on the page as 80px on longest edge, so it looks like this length is hard coded into the page. I've tried to figure out where this is set myself, but haven't had any luck. Could you please either set it to 100px or simply turn it off so it's determined by the size of the images themselves.

**Comment by nigelgbanks** [comment]
I took a look into this a bit on Friday and wasn't able to sort out where where the dimensions were being forcefully set. It's not occurring in the theme or the timeline module. Altering the settings for the image display in the view or system doesn't seem to have an affect either. This  is going to take some more digging.

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
Looks good. Can you confirm that this is determined by the size of the images? If so, you can close this ticket.

**Comment by nigelgbanks** [comment]
It was a combination of factors, but now is up to a max of 100px on the longest side for the images.

**Comment by awisnicki** [comment]
Sorry, what I was trying to suggest is that I'd prefer that it be determined by the size of the image rather than set at a specific size. Is that possible? Right now the images are all 100px on the longest edge, but I may find I want to increase this size in the future. Feel free to reopen this if necessary.

**Comment by nigelgbanks** [comment]
Oh ok, I'll change it to work like that.

**Comment by nigelgbanks** [comment]
K it now apply's no changes to the images displayed.

**Comment by awisnicki** [comment]
Great, thank you! Let's chat about what you think might be the optimal image size when next we meet. It's very easy to regenerate the thumbnails
