### ISSUE TITLE
Manuscript Viewer: Ordered List of Spectral Images

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#84]
I'm creating this ticket so you have an easy reference for the order of images in the spectral image viewer. No single page will have all these renderings, so only those that are available for the given page should show up in the dropdown.

color
ratio_by_0940
pca321r_pcolor
pca421r_pcolor
pca621r_pcolor
pca721r_pcolor
pseudoratio_0505-0780
pseudo_0505-0780
pseudo_0780
pseudo_0780_by_0940
pseudo_940_by_592
pseudoBY_940_by_592
red_green
PCA_pseudo_(NLS10703_052_ stats)
PCA_pseudo_(NLS10703_054_ stats)
ICA_pseudo_(DLC297d_trans)
ICA_pseudo_(NLS10703_trans)
pca321r_adapThresh
pca321r_adapThresh_multiply
pca321r
pca321r_1_adapThresh_multiply
pca321r_1
pca321r_2_adapThresh_multiply
pca321r_2
pca421r_adapThresh_multiply
pca421r
pca621r_adapThresh_multiply
pca621r
pca721r_adapThresh_multiply
pca721r
intercept
RARR
RAPRratio
RAIPratio
RIRL
color_raking
pseudo_raking_irdiff
raking_irdiff
sharpie_0505-0780
sharpieratio_0505-0780
IC1_(DLC297d_trans)
IC2_(DLC297d_trans)
IC3_(DLC297d_trans)
IC4_(DLC297d_trans)
IC5_(DLC297d_trans)

**Comment by awisnicki** [comment]
I forgot to tell you that we ended up shortening a lot of these names and that these new short names should be used in the viewer. I hope this will be OK to change the names. I attach a spreadsheet which shows you the short name for each of the images above. Also, please remember that the images should be shown (when present) in the order given above. The order is also in the spreadsheet for the new short names.
[long-and-short-names.xlsx](https://github.com/livingstoneonline/livingstoneonline/files/563237/long-and-short-names.xlsx)

**Comment by nigelgbanks** [comment]
This is fine as long as the file names don't change on the FTP server, as the file name is how we derive the identifier and determine what's to be copied over.

**Comment by awisnicki** [comment]
great. feel free to close this ticket once the dropdowns are sorted out.

**Comment by nigelgbanks** [comment]
Should be sorted on stage now.

**Comment by awisnicki** [comment]
Looks good. Thank you.
