### ISSUE TITLE
Addressee page: minor issue

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#85]
On the Addressee page (http://livingstoneonline.org/browse/addressee), & is coming up as &amp;

Take a look at, for instance:

Ancient &amp; Honourable Company of Turners, Ladies &amp; Gentlemen

**Comment by nigelgbanks** [comment]
Should be sorted on stage now.

**Comment by awisnicki** [comment]
Looks good. Thanks! Please push up to prod.
