### ISSUE TITLE
Multiple XSLT Viewer: further adjustments

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#87]
Please make the following additional adjustments to the viewer:
1. When we go to mobile, turn off the level 2 image from appearing.
2. The panes are slightly too high. Assuming that the current height is 100%, please reduce to about 90%.
3. Please make the panes slightly wider. See the screen shot below for the two adjustments I've made, but please use your discretion on this. The point is to make it slightly wider.
![screen shot 2016-10-31 at 17 36 05](https://cloud.githubusercontent.com/assets/12518623/19874123/e6761d0e-9f90-11e6-9dc5-3c283ff33dc4.png)

**Comment by nigelgbanks** [comment]
Changes on stage ready for review.

**Comment by awisnicki** [comment]
Overall the tweaks here look good. I've got one more that's related, but I'll put it with the other changes for the Multi Viewer and so am closing this ticket.
