### ISSUE TITLE
Sticky Header: padding needed

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#88]
See image. The third item needs some left and right padding on all pages (i.e., the gray box should be slightly wider as it's running up against the text).
![screen shot 2016-10-31 at 17 42 10](https://cloud.githubusercontent.com/assets/12518623/19874213/a4ee1048-9f91-11e6-9e57-928fec59e237.png)

**Comment by nigelgbanks** [comment]
Should be sorted on stage now.

**Comment by awisnicki** [comment]
Looks good. Thank you!
