### ISSUE TITLE
Sticky header: remove transparency

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#89]
When our new critical edition dropdown scrolls through the sticky header on level 3 pages, the header is transparent when it shouldn't be. See attached screen shot.
![screen shot 2016-11-01 at 9 48 26](https://cloud.githubusercontent.com/assets/12518623/19906428/bdf1f840-a048-11e6-83ad-b47d2780edd3.png)

**Comment by nigelgbanks** [comment]
Should be sorted on stage now.

**Comment by awisnicki** [comment]
Yes, resolved. Thank you!
