### ISSUE TITLE
Catalogue: access for spectral images

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#91]
The catalogue needs to have the download arrows/download functionality added to the display. Clicking on an arrow for spectral images would open the new download overlay.
![screen shot 2016-11-02 at 12 14 39](https://cloud.githubusercontent.com/assets/12518623/19939312/5d172c26-a0f6-11e6-8d26-723c5f20918e.png)

**Comment by nigelgbanks** [comment]
Should be sorted on stage now.

**Comment by awisnicki** [comment]
Looks good. Thank you
