### ISSUE TITLE
Spectral image download page: adjustments

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#92]
See image below for tweaks to the download page.
![screen shot 2016-11-02 at 12 20 13](https://cloud.githubusercontent.com/assets/12518623/19940023/4422006c-a0f9-11e6-8e55-42ab80730e46.png)

**Comment by nigelgbanks** [comment]
Ready for review on stage.

**Comment by awisnicki** [comment]
Still some adjustments needed. See attached.
![screen shot 2016-11-04 at 18 04 21](https://cloud.githubusercontent.com/assets/12518623/20025146/c77aa8b2-a2b9-11e6-9ac3-bc6e2d75f3a0.png)

**Comment by nigelgbanks** [comment]
Hmm I can't seem to reproduce the scroll bar on firefox chrome or safari?

**Comment by awisnicki** [comment]
I'm using Firefox 49.0. The gray border both at bottom and at right is for the scroll bar. If on a given page the scroll bar is needed (as in my screen shot above), then it appears inside of that gray bar, so clearly that's what it's for; at the bottom it's obviously for side to side scrolling. That said, given that it's light gray, it's fairly low key and innocuous so if you can't figure out how to turn it off when not needed, then we can just leave it.

**Comment by nigelgbanks** [comment]
Ready to review on stage (still couldn't get the scroll bar issue to occur).

**Comment by awisnicki** [comment]
This also looks fantastic. Just a few additional tweaks:

1) Put some padding above the title (1.5em). Right now the title is too close to the top.
2) As this narrows, please watch that the X box in the upper right-hand corner does not go over the text (see screen shot below).

![screen shot 2016-11-11 at 20 56 59](https://cloud.githubusercontent.com/assets/12518623/20235194/7952fbe2-a851-11e6-9e37-c5793d62c9ca.png)

3) At the most narrow width, the download files should not break over two lines (see screen shot). There's enough room for them to stay on one line.

![screen shot 2016-11-11 at 20 57 54](https://cloud.githubusercontent.com/assets/12518623/20235201/a8bca914-a851-11e6-8a11-a6dab15ec499.png)

**Comment by nigelgbanks** [comment]
> 1) Put some padding above the title (1.5em). Right now the title is too close to the top.

K, changed from 1em to 1.5em.

> 2) As this narrows, please watch that the X box in the upper right-hand corner does not go over the text (see screen shot below).

With the additional top padding it doesn't seem to happen anymore.

> 3)  At the most narrow width, the download files should not break over two lines (see screen shot). There's enough room for them to stay on one line.

Should be sorted now.

**Comment by awisnicki** [comment]
> K, changed from 1em to 1.5em.

Actually I meant add 1.5em to what was there already. Looking at this now, however, you could make it 3em total from the top, rather than 1.5em total from the top as now.

> With the additional top padding it doesn't seem to happen anymore.

Unfortunately, still happening. See attached this is an issue on longer title. Moving it farther down, as I just asked, may help.

![screen shot 2016-11-13 at 14 18 58](https://cloud.githubusercontent.com/assets/12518623/20246317/71062700-a9ac-11e6-8258-96aa57ca95ff.png)

> Should be sorted now.

Indeed, the line breaking is no longer happening

**Comment by nigelgbanks** [comment]
K now at 3em on stage.

**Comment by awisnicki** [comment]
OK, that is fixed, but on reviewing I still see two issues. See screenshot.
![screen shot 2016-11-13 at 20 00 04](https://cloud.githubusercontent.com/assets/12518623/20248447/3675de84-a9dc-11e6-9f8b-ef8814663a3b.png)

**Comment by nigelgbanks** [comment]
Ready to review on stage.

**Comment by awisnicki** [comment]
This one's a wrap. Thank you for your work on this!
