### ISSUE TITLE
Spectral image viewer: adjustments

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#95]
See attached for adjustments, but in short here is the list:

1. Remove all caps in spectral image dropdowns.
2. Have the image dropdown say "Select spectral image type" by default
3. Please put a thin white line down the middle to separate the two panes.
4. Put spectral images in the order given. "spectral_ratio" should be the default on the right.
5. Put the lightning flash (in black) after the word "Compare" in that button for a little clarity as to what the button does.

![screen shot 2016-11-02 at 12 43 15](https://cloud.githubusercontent.com/assets/12518623/19941356/d5738be0-a0fd-11e6-8aac-4d9d6314062f.png)

**Comment by nigelgbanks** [comment]
> Have the image dropdown say "Select spectral image type" by default

Are you sure you wish to have that dropdown say that? As a selection is presented automatically and it's not possible to show a non-selection?

**Comment by awisnicki** [comment]
The concern is that user are not going to know what they spectral image name is/means. What about some text that appears on hover, as we have already set up for when the transcription button is not clickable? We could do the same thing, working/looking the exact same way, and the hover would say "Select a spectral image type"

**Comment by nigelgbanks** [comment]
Yup I can add that.

**Comment by nigelgbanks** [comment]
Added a tooltip, ready for review on stage.

**Comment by awisnicki** [comment]
Still some adjustments needed. See two attachments.
![screen shot 2016-11-04 at 18 25 29](https://cloud.githubusercontent.com/assets/12518623/20025549/56af1eac-a2bd-11e6-8e23-ec265e12a91f.png)
![screen shot 2016-11-04 at 18 14 34](https://cloud.githubusercontent.com/assets/12518623/20025550/585ce0fe-a2bd-11e6-970c-31eb844c1716.png)

**Comment by nigelgbanks** [comment]
Even without the padding, and the new text the tooltip is larger than the select field.

<img width="617" alt="screen shot 2016-11-08 at 14 23 39" src="https://cloud.githubusercontent.com/assets/487373/20102711/fecbf89a-a5be-11e6-8240-5e7181cff77a.png">

**Comment by awisnicki** [comment]
What about just slightly widening the spectral image dropdown? That would also allow you to put a touch of left-right padding on the tooltip.

**Comment by nigelgbanks** [comment]
Doing so causes the button row to break to the next line.

<img width="621" alt="screen shot 2016-11-08 at 15 57 04" src="https://cloud.githubusercontent.com/assets/487373/20106146/0f0c975c-a5cc-11e6-84cb-f95fbd2efe4e.png">

**Comment by awisnicki** [comment]
What about reducing the size of the text in the tooltip one notch? Also, please de-capitalize the first "S" in the tooltip.

**Comment by nigelgbanks** [comment]
Ready for review on stage.

**Comment by awisnicki** [comment]
I think you resolved everything here, so I'm closing this ticket. Thank you.
