### ISSUE TITLE
Spectral image viewer: transcriptions

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#96]
There is an issue with viewing spectral images in that if you choose a page other than the first one (for instance, page 2 or page 3 -- i.e., I'm not talking about choosing a different spectral image), then look at the transcription it doesn't not automatically adjust to the page that you are on.

**Comment by nigelgbanks** [comment]
Ready for review on stage.

**Comment by awisnicki** [comment]
Thanks! This looks to be resolved except for the point I noted in the other ticket.
